///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_8
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyNavigationToDate recording.
    /// </summary>
    [TestModule("67d3fc00-50ab-4996-9f4e-3d206f52120d", ModuleType.Recording, 1)]
    public partial class VerifyNavigationToDate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_8Repository repository.
        /// </summary>
        public static Sprint_9_8Repository repo = Sprint_9_8Repository.Instance;

        static VerifyNavigationToDate instance = new VerifyNavigationToDate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyNavigationToDate()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyNavigationToDate Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2023973Test.ChoixDate1.EdtYear' at 33;8.", repo.CWork2023973Test.ChoixDate1.EdtYearInfo, new RecordItemIndex(0));
            repo.CWork2023973Test.ChoixDate1.EdtYear.Click("33;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'CWork2023973Test.ChoixDate1.EdtYear'.", repo.CWork2023973Test.ChoixDate1.EdtYearInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.CWork2023973Test.ChoixDate1.EdtYear);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2023' with focus on 'CWork2023973Test.ChoixDate1.EdtYear'.", repo.CWork2023973Test.ChoixDate1.EdtYearInfo, new RecordItemIndex(2));
            repo.CWork2023973Test.ChoixDate1.EdtYear.PressKeys("2023");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2023973Test.ChoixDate1.EdtMonth' at 17;9.", repo.CWork2023973Test.ChoixDate1.EdtMonthInfo, new RecordItemIndex(3));
            repo.CWork2023973Test.ChoixDate1.EdtMonth.Click("17;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'CWork2023973Test.ChoixDate1.EdtMonth'.", repo.CWork2023973Test.ChoixDate1.EdtMonthInfo, new RecordItemIndex(4));
            Keyboard.PrepareFocus(repo.CWork2023973Test.ChoixDate1.EdtMonth);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 16, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'CWork2023973Test.ChoixDate1.EdtMonth'.", repo.CWork2023973Test.ChoixDate1.EdtMonthInfo, new RecordItemIndex(5));
            repo.CWork2023973Test.ChoixDate1.EdtMonth.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2023973Test.ChoixDate1.UpdateCal' at 42;12.", repo.CWork2023973Test.ChoixDate1.UpdateCalInfo, new RecordItemIndex(6));
            repo.CWork2023973Test.ChoixDate1.UpdateCal.Click("42;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (RawText='janvier 2023') on item 'CWork2023973Test.ChoixDate1.Janvier2023'.", repo.CWork2023973Test.ChoixDate1.Janvier2023Info, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.CWork2023973Test.ChoixDate1.Janvier2023Info, "RawText", "janvier 2023");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
