///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sprint_9_8_4
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Sprint_9_8_4Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3fea9cd6-74e2-40e9-8e9c-a1a51cddc404")]
    public partial class Sprint_9_8_4Repository : RepoGenBaseFolder
    {
        static Sprint_9_8_4Repository instance = new Sprint_9_8_4Repository();
        Sprint_9_8_4RepositoryFolders.CWork2024983AppFolder _cwork2024983;
        Sprint_9_8_4RepositoryFolders.AjoutDeCNCSAppFolder _ajoutdecncs;
        Sprint_9_8_4RepositoryFolders.NouveauDocumentAppFolder _nouveaudocument;
        Sprint_9_8_4RepositoryFolders.ProprietesDunDocumentAppFolder _proprietesdundocument;
        Sprint_9_8_4RepositoryFolders.SelectionnerUneCncAppFolder _selectionnerunecnc;
        Sprint_9_8_4RepositoryFolders.CworkAppFolder _cwork;
        Sprint_9_8_4RepositoryFolders.SauvegardeDesModificationsAppFolder _sauvegardedesmodifications;

        /// <summary>
        /// Gets the singleton class instance representing the Sprint_9_8_4Repository element repository.
        /// </summary>
        [RepositoryFolder("3fea9cd6-74e2-40e9-8e9c-a1a51cddc404")]
        public static Sprint_9_8_4Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Sprint_9_8_4Repository() 
            : base("Sprint_9_8_4Repository", "/", null, 0, false, "3fea9cd6-74e2-40e9-8e9c-a1a51cddc404", ".\\RepositoryImages\\Sprint_9_8_4Repository3fea9cd6.rximgres")
        {
            _cwork2024983 = new Sprint_9_8_4RepositoryFolders.CWork2024983AppFolder(this);
            _ajoutdecncs = new Sprint_9_8_4RepositoryFolders.AjoutDeCNCSAppFolder(this);
            _nouveaudocument = new Sprint_9_8_4RepositoryFolders.NouveauDocumentAppFolder(this);
            _proprietesdundocument = new Sprint_9_8_4RepositoryFolders.ProprietesDunDocumentAppFolder(this);
            _selectionnerunecnc = new Sprint_9_8_4RepositoryFolders.SelectionnerUneCncAppFolder(this);
            _cwork = new Sprint_9_8_4RepositoryFolders.CworkAppFolder(this);
            _sauvegardedesmodifications = new Sprint_9_8_4RepositoryFolders.SauvegardeDesModificationsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3fea9cd6-74e2-40e9-8e9c-a1a51cddc404")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The CWork2024983 folder.
        /// </summary>
        [RepositoryFolder("28efefbc-27eb-4fbd-8543-6c4ed3ceafbe")]
        public virtual Sprint_9_8_4RepositoryFolders.CWork2024983AppFolder CWork2024983
        {
            get { return _cwork2024983; }
        }

        /// <summary>
        /// The AjoutDeCNCS folder.
        /// </summary>
        [RepositoryFolder("f2c50436-a268-472f-b7b6-9fe7e1b5d311")]
        public virtual Sprint_9_8_4RepositoryFolders.AjoutDeCNCSAppFolder AjoutDeCNCS
        {
            get { return _ajoutdecncs; }
        }

        /// <summary>
        /// The NouveauDocument folder.
        /// </summary>
        [RepositoryFolder("c48a7c74-d7fa-47ad-ac22-b0d660382dd6")]
        public virtual Sprint_9_8_4RepositoryFolders.NouveauDocumentAppFolder NouveauDocument
        {
            get { return _nouveaudocument; }
        }

        /// <summary>
        /// The ProprietesDunDocument folder.
        /// </summary>
        [RepositoryFolder("877ab74d-7c7d-40e9-b914-ead36713efbe")]
        public virtual Sprint_9_8_4RepositoryFolders.ProprietesDunDocumentAppFolder ProprietesDunDocument
        {
            get { return _proprietesdundocument; }
        }

        /// <summary>
        /// The SelectionnerUneCnc folder.
        /// </summary>
        [RepositoryFolder("44c50f0e-b6db-4e0f-8d27-c1bf16335796")]
        public virtual Sprint_9_8_4RepositoryFolders.SelectionnerUneCncAppFolder SelectionnerUneCnc
        {
            get { return _selectionnerunecnc; }
        }

        /// <summary>
        /// The Cwork folder.
        /// </summary>
        [RepositoryFolder("51906420-ee27-4514-bede-28db9b630134")]
        public virtual Sprint_9_8_4RepositoryFolders.CworkAppFolder Cwork
        {
            get { return _cwork; }
        }

        /// <summary>
        /// The SauvegardeDesModifications folder.
        /// </summary>
        [RepositoryFolder("4ceec5ee-6e38-4bc1-8253-efc4a14126d3")]
        public virtual Sprint_9_8_4RepositoryFolders.SauvegardeDesModificationsAppFolder SauvegardeDesModifications
        {
            get { return _sauvegardedesmodifications; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Sprint_9_8_4RepositoryFolders
    {
        /// <summary>
        /// The CWork2024983AppFolder folder.
        /// </summary>
        [RepositoryFolder("28efefbc-27eb-4fbd-8543-6c4ed3ceafbe")]
        public partial class CWork2024983AppFolder : RepoGenBaseFolder
        {
            Sprint_9_8_4RepositoryFolders.Prog1CNCA0EDITECnc1Folder _prog1cnca0editecnc1;
            Sprint_9_8_4RepositoryFolders.Atelier1Folder _atelier1;
            RepoItemInfo _baddInfo;
            RepoItemInfo _tadvsmoothtogglebuttonInfo;
            RepoItemInfo _bnewInfo;
            RepoItemInfo _partsviewInfo;
            RepoItemInfo _tadvsmoothtogglebutton1Info;

            /// <summary>
            /// Creates a new CWork2024983  folder.
            /// </summary>
            public CWork2024983AppFolder(RepoGenBaseFolder parentFolder) :
                    base("CWork2024983", "/form[@name='CworkMainForm']", parentFolder, 30000, null, true, "28efefbc-27eb-4fbd-8543-6c4ed3ceafbe", "")
            {
                _prog1cnca0editecnc1 = new Sprint_9_8_4RepositoryFolders.Prog1CNCA0EDITECnc1Folder(this);
                _atelier1 = new Sprint_9_8_4RepositoryFolders.Atelier1Folder(this);
                _baddInfo = new RepoItemInfo(this, "BAdd", "element[@name='pages']/?/?/form[@name='CncViewForm']/element[@name='AdvDockPanel1']/element[@name='MainCNCToolbar']/element[@name='bAdd']", "", 30000, null, "097035af-fb51-4bb4-adcd-8b09170a6f88");
                _tadvsmoothtogglebuttonInfo = new RepoItemInfo(this, "TAdvSmoothToggleButton", "?/?/element[@instance='2']", "", 30000, null, "f587d5a4-8a10-4051-9801-8c0a58c31f75");
                _bnewInfo = new RepoItemInfo(this, "BNew", "element[@name='pages']/?/?/form[@name='DBViewForm']/element[@name='BarPanel']/element[@name='RecordToolBar']/element[@name='bNew']", "", 30000, null, "13739f5f-99ae-4cba-87c5-5ab4c6c081f3");
                _partsviewInfo = new RepoItemInfo(this, "PartsView", "element[@name='pages']/?/?/form[@name='DBViewForm']/container[@name='PartsViewFrame']/list[@name='PartsView']", "", 30000, null, "f7c47ab1-f413-4732-9b34-5be64fbd1c23");
                _tadvsmoothtogglebutton1Info = new RepoItemInfo(this, "TAdvSmoothToggleButton1", "container[@name='PaButtonBar']/element[2]", "", 30000, null, "d8c6e021-b19e-4b21-b76c-461988048885");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("28efefbc-27eb-4fbd-8543-6c4ed3ceafbe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("28efefbc-27eb-4fbd-8543-6c4ed3ceafbe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BAdd item.
            /// </summary>
            [RepositoryItem("097035af-fb51-4bb4-adcd-8b09170a6f88")]
            public virtual Ranorex.Unknown BAdd
            {
                get
                {
                    return _baddInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BAdd item info.
            /// </summary>
            [RepositoryItemInfo("097035af-fb51-4bb4-adcd-8b09170a6f88")]
            public virtual RepoItemInfo BAddInfo
            {
                get
                {
                    return _baddInfo;
                }
            }

            /// <summary>
            /// The TAdvSmoothToggleButton item.
            /// </summary>
            [RepositoryItem("f587d5a4-8a10-4051-9801-8c0a58c31f75")]
            public virtual Ranorex.Unknown TAdvSmoothToggleButton
            {
                get
                {
                    return _tadvsmoothtogglebuttonInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TAdvSmoothToggleButton item info.
            /// </summary>
            [RepositoryItemInfo("f587d5a4-8a10-4051-9801-8c0a58c31f75")]
            public virtual RepoItemInfo TAdvSmoothToggleButtonInfo
            {
                get
                {
                    return _tadvsmoothtogglebuttonInfo;
                }
            }

            /// <summary>
            /// The BNew item.
            /// </summary>
            [RepositoryItem("13739f5f-99ae-4cba-87c5-5ab4c6c081f3")]
            public virtual Ranorex.Unknown BNew
            {
                get
                {
                    return _bnewInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BNew item info.
            /// </summary>
            [RepositoryItemInfo("13739f5f-99ae-4cba-87c5-5ab4c6c081f3")]
            public virtual RepoItemInfo BNewInfo
            {
                get
                {
                    return _bnewInfo;
                }
            }

            /// <summary>
            /// The PartsView item.
            /// </summary>
            [RepositoryItem("f7c47ab1-f413-4732-9b34-5be64fbd1c23")]
            public virtual Ranorex.List PartsView
            {
                get
                {
                    return _partsviewInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The PartsView item info.
            /// </summary>
            [RepositoryItemInfo("f7c47ab1-f413-4732-9b34-5be64fbd1c23")]
            public virtual RepoItemInfo PartsViewInfo
            {
                get
                {
                    return _partsviewInfo;
                }
            }

            /// <summary>
            /// The TAdvSmoothToggleButton1 item.
            /// </summary>
            [RepositoryItem("d8c6e021-b19e-4b21-b76c-461988048885")]
            public virtual Ranorex.Unknown TAdvSmoothToggleButton1
            {
                get
                {
                    return _tadvsmoothtogglebutton1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TAdvSmoothToggleButton1 item info.
            /// </summary>
            [RepositoryItemInfo("d8c6e021-b19e-4b21-b76c-461988048885")]
            public virtual RepoItemInfo TAdvSmoothToggleButton1Info
            {
                get
                {
                    return _tadvsmoothtogglebutton1Info;
                }
            }

            /// <summary>
            /// The Prog1CNCA0EDITECnc1 folder.
            /// </summary>
            [RepositoryFolder("b89a0cfc-a080-46a1-ba2b-a2dca26d7081")]
            public virtual Sprint_9_8_4RepositoryFolders.Prog1CNCA0EDITECnc1Folder Prog1CNCA0EDITECnc1
            {
                get { return _prog1cnca0editecnc1; }
            }

            /// <summary>
            /// The Atelier1 folder.
            /// </summary>
            [RepositoryFolder("ede9b4e7-01ab-4150-a9bd-51c8391d2e62")]
            public virtual Sprint_9_8_4RepositoryFolders.Atelier1Folder Atelier1
            {
                get { return _atelier1; }
            }
        }

        /// <summary>
        /// The Prog1CNCA0EDITECnc1Folder folder.
        /// </summary>
        [RepositoryFolder("b89a0cfc-a080-46a1-ba2b-a2dca26d7081")]
        public partial class Prog1CNCA0EDITECnc1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _colormemoInfo;
            RepoItemInfo _bcloseInfo;
            RepoItemInfo _bsaveInfo;

            /// <summary>
            /// Creates a new Prog1CNCA0EDITECnc1  folder.
            /// </summary>
            public Prog1CNCA0EDITECnc1Folder(RepoGenBaseFolder parentFolder) :
                    base("Prog1CNCA0EDITECnc1", "element[@name='pages']/?/?/form[@name='DocumentViewForm']", parentFolder, 30000, null, false, "b89a0cfc-a080-46a1-ba2b-a2dca26d7081", "")
            {
                _colormemoInfo = new RepoItemInfo(this, "ColorMemo", "container[@name='PanelMemo']/element[@name='ColorMemo']", "", 30000, null, "ca248cd8-9823-40b3-959d-27197d6f0fe7");
                _bcloseInfo = new RepoItemInfo(this, "BClose", "element[@name='BarPanel']/element[@name='RecordToolBar']/element[@name='bClose']", "", 30000, null, "36c7d274-7a42-4d47-b5eb-53a4334dbf95");
                _bsaveInfo = new RepoItemInfo(this, "BSave", "element[@name='BarPanel']/element[@name='RecordToolBar']/element[@name='bSave']", "", 30000, null, "db98c70f-f769-4f84-9601-a13fa2a1efa8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b89a0cfc-a080-46a1-ba2b-a2dca26d7081")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b89a0cfc-a080-46a1-ba2b-a2dca26d7081")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ColorMemo item.
            /// </summary>
            [RepositoryItem("ca248cd8-9823-40b3-959d-27197d6f0fe7")]
            public virtual Ranorex.Unknown ColorMemo
            {
                get
                {
                    return _colormemoInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ColorMemo item info.
            /// </summary>
            [RepositoryItemInfo("ca248cd8-9823-40b3-959d-27197d6f0fe7")]
            public virtual RepoItemInfo ColorMemoInfo
            {
                get
                {
                    return _colormemoInfo;
                }
            }

            /// <summary>
            /// The BClose item.
            /// </summary>
            [RepositoryItem("36c7d274-7a42-4d47-b5eb-53a4334dbf95")]
            public virtual Ranorex.Unknown BClose
            {
                get
                {
                    return _bcloseInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BClose item info.
            /// </summary>
            [RepositoryItemInfo("36c7d274-7a42-4d47-b5eb-53a4334dbf95")]
            public virtual RepoItemInfo BCloseInfo
            {
                get
                {
                    return _bcloseInfo;
                }
            }

            /// <summary>
            /// The BSave item.
            /// </summary>
            [RepositoryItem("db98c70f-f769-4f84-9601-a13fa2a1efa8")]
            public virtual Ranorex.Unknown BSave
            {
                get
                {
                    return _bsaveInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BSave item info.
            /// </summary>
            [RepositoryItemInfo("db98c70f-f769-4f84-9601-a13fa2a1efa8")]
            public virtual RepoItemInfo BSaveInfo
            {
                get
                {
                    return _bsaveInfo;
                }
            }
        }

        /// <summary>
        /// The Atelier1Folder folder.
        /// </summary>
        [RepositoryFolder("ede9b4e7-01ab-4150-a9bd-51c8391d2e62")]
        public partial class Atelier1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _cnc2Info;
            RepoItemInfo _cnc3Info;
            RepoItemInfo _cnc4Info;
            RepoItemInfo _cnc1Info;
            RepoItemInfo _rawtextdo0percentInfo;
            RepoItemInfo _cnc1cnc2cnc3cnc4do0peInfo;
            RepoItemInfo _rawtextdo0percent1Info;

            /// <summary>
            /// Creates a new Atelier1  folder.
            /// </summary>
            public Atelier1Folder(RepoGenBaseFolder parentFolder) :
                    base("Atelier1", "element[@name='pages']/?/?/form[@name='CncViewForm']", parentFolder, 30000, null, false, "ede9b4e7-01ab-4150-a9bd-51c8391d2e62", "")
            {
                _cnc2Info = new RepoItemInfo(this, "Cnc2", "element[@name='StationsTiles']/rawtext[@rawtext='Cnc-2']", "", 30000, null, "24d59137-e024-445e-bab4-61afe34d7b0f");
                _cnc3Info = new RepoItemInfo(this, "Cnc3", "element[@name='StationsTiles']/rawtext[@rawtext='Cnc-3']", "", 30000, null, "28883c49-5e3d-4a16-aca6-aaa980dd3659");
                _cnc4Info = new RepoItemInfo(this, "Cnc4", "element[@name='StationsTiles']/rawtext[@rawtext='Cnc-4']", "", 30000, null, "899cbcc1-66c3-4e65-9bd4-ed716ef83365");
                _cnc1Info = new RepoItemInfo(this, "Cnc1", "element[@name='StationsTiles']/rawtext[@rawtext='Cnc-1']", "", 30000, null, "c7762280-3a20-42db-aa26-b7d770b2fc73");
                _rawtextdo0percentInfo = new RepoItemInfo(this, "RawTextDO0Percent", "element[@name='StationsTiles']/rawtext[@column='1']", "", 30000, null, "772a47ac-01a4-4414-b4ae-a9b117530c15");
                _cnc1cnc2cnc3cnc4do0peInfo = new RepoItemInfo(this, "Cnc1Cnc2Cnc3Cnc4DO0Pe", "element[@name='StationsTiles']/rawtextblock[@caption>'Cnc-1Cnc-2Cnc-3Cnc-4']", "", 30000, null, "7cb154ec-d737-4a4d-b41d-2d3525d5e029");
                _rawtextdo0percent1Info = new RepoItemInfo(this, "RawTextDO0Percent1", "element[@name='StationsTiles']/rawtext[@column='5']", "", 30000, null, "917b9aec-14a0-439a-8a88-fceda0441953");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ede9b4e7-01ab-4150-a9bd-51c8391d2e62")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ede9b4e7-01ab-4150-a9bd-51c8391d2e62")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cnc2 item.
            /// </summary>
            [RepositoryItem("24d59137-e024-445e-bab4-61afe34d7b0f")]
            public virtual Ranorex.RawText Cnc2
            {
                get
                {
                    return _cnc2Info.CreateAdapter<Ranorex.RawText>(true);
                }
            }

            /// <summary>
            /// The Cnc2 item info.
            /// </summary>
            [RepositoryItemInfo("24d59137-e024-445e-bab4-61afe34d7b0f")]
            public virtual RepoItemInfo Cnc2Info
            {
                get
                {
                    return _cnc2Info;
                }
            }

            /// <summary>
            /// The Cnc3 item.
            /// </summary>
            [RepositoryItem("28883c49-5e3d-4a16-aca6-aaa980dd3659")]
            public virtual Ranorex.RawText Cnc3
            {
                get
                {
                    return _cnc3Info.CreateAdapter<Ranorex.RawText>(true);
                }
            }

            /// <summary>
            /// The Cnc3 item info.
            /// </summary>
            [RepositoryItemInfo("28883c49-5e3d-4a16-aca6-aaa980dd3659")]
            public virtual RepoItemInfo Cnc3Info
            {
                get
                {
                    return _cnc3Info;
                }
            }

            /// <summary>
            /// The Cnc4 item.
            /// </summary>
            [RepositoryItem("899cbcc1-66c3-4e65-9bd4-ed716ef83365")]
            public virtual Ranorex.RawText Cnc4
            {
                get
                {
                    return _cnc4Info.CreateAdapter<Ranorex.RawText>(true);
                }
            }

            /// <summary>
            /// The Cnc4 item info.
            /// </summary>
            [RepositoryItemInfo("899cbcc1-66c3-4e65-9bd4-ed716ef83365")]
            public virtual RepoItemInfo Cnc4Info
            {
                get
                {
                    return _cnc4Info;
                }
            }

            /// <summary>
            /// The Cnc1 item.
            /// </summary>
            [RepositoryItem("c7762280-3a20-42db-aa26-b7d770b2fc73")]
            public virtual Ranorex.RawText Cnc1
            {
                get
                {
                    return _cnc1Info.CreateAdapter<Ranorex.RawText>(true);
                }
            }

            /// <summary>
            /// The Cnc1 item info.
            /// </summary>
            [RepositoryItemInfo("c7762280-3a20-42db-aa26-b7d770b2fc73")]
            public virtual RepoItemInfo Cnc1Info
            {
                get
                {
                    return _cnc1Info;
                }
            }

            /// <summary>
            /// The RawTextDO0Percent item.
            /// </summary>
            [RepositoryItem("772a47ac-01a4-4414-b4ae-a9b117530c15")]
            public virtual Ranorex.RawText RawTextDO0Percent
            {
                get
                {
                    return _rawtextdo0percentInfo.CreateAdapter<Ranorex.RawText>(true);
                }
            }

            /// <summary>
            /// The RawTextDO0Percent item info.
            /// </summary>
            [RepositoryItemInfo("772a47ac-01a4-4414-b4ae-a9b117530c15")]
            public virtual RepoItemInfo RawTextDO0PercentInfo
            {
                get
                {
                    return _rawtextdo0percentInfo;
                }
            }

            /// <summary>
            /// The Cnc1Cnc2Cnc3Cnc4DO0Pe item.
            /// </summary>
            [RepositoryItem("7cb154ec-d737-4a4d-b41d-2d3525d5e029")]
            public virtual Ranorex.RawTextBlock Cnc1Cnc2Cnc3Cnc4DO0Pe
            {
                get
                {
                    return _cnc1cnc2cnc3cnc4do0peInfo.CreateAdapter<Ranorex.RawTextBlock>(true);
                }
            }

            /// <summary>
            /// The Cnc1Cnc2Cnc3Cnc4DO0Pe item info.
            /// </summary>
            [RepositoryItemInfo("7cb154ec-d737-4a4d-b41d-2d3525d5e029")]
            public virtual RepoItemInfo Cnc1Cnc2Cnc3Cnc4DO0PeInfo
            {
                get
                {
                    return _cnc1cnc2cnc3cnc4do0peInfo;
                }
            }

            /// <summary>
            /// The RawTextDO0Percent1 item.
            /// </summary>
            [RepositoryItem("917b9aec-14a0-439a-8a88-fceda0441953")]
            public virtual Ranorex.RawText RawTextDO0Percent1
            {
                get
                {
                    return _rawtextdo0percent1Info.CreateAdapter<Ranorex.RawText>(true);
                }
            }

            /// <summary>
            /// The RawTextDO0Percent1 item info.
            /// </summary>
            [RepositoryItemInfo("917b9aec-14a0-439a-8a88-fceda0441953")]
            public virtual RepoItemInfo RawTextDO0Percent1Info
            {
                get
                {
                    return _rawtextdo0percent1Info;
                }
            }
        }

        /// <summary>
        /// The AjoutDeCNCSAppFolder folder.
        /// </summary>
        [RepositoryFolder("f2c50436-a268-472f-b7b6-9fe7e1b5d311")]
        public partial class AjoutDeCNCSAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cnccountInfo;
            RepoItemInfo _baddInfo;

            /// <summary>
            /// Creates a new AjoutDeCNCS  folder.
            /// </summary>
            public AjoutDeCNCSAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AjoutDeCNCS", "/form[@name='AddCncForm']", parentFolder, 30000, null, true, "f2c50436-a268-472f-b7b6-9fe7e1b5d311", "")
            {
                _cnccountInfo = new RepoItemInfo(this, "CNCCount", "?/?/text[@name='CNCCount']", "", 30000, null, "3aafade5-f44b-43da-ad78-97a041ac2060");
                _baddInfo = new RepoItemInfo(this, "BAdd", "?/?/element[@name='bAdd']", "", 30000, null, "fdf6b9a1-e7f4-4874-b186-c554d5f7f8f8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f2c50436-a268-472f-b7b6-9fe7e1b5d311")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f2c50436-a268-472f-b7b6-9fe7e1b5d311")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CNCCount item.
            /// </summary>
            [RepositoryItem("3aafade5-f44b-43da-ad78-97a041ac2060")]
            public virtual Ranorex.Text CNCCount
            {
                get
                {
                    return _cnccountInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CNCCount item info.
            /// </summary>
            [RepositoryItemInfo("3aafade5-f44b-43da-ad78-97a041ac2060")]
            public virtual RepoItemInfo CNCCountInfo
            {
                get
                {
                    return _cnccountInfo;
                }
            }

            /// <summary>
            /// The BAdd item.
            /// </summary>
            [RepositoryItem("fdf6b9a1-e7f4-4874-b186-c554d5f7f8f8")]
            public virtual Ranorex.Unknown BAdd
            {
                get
                {
                    return _baddInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BAdd item info.
            /// </summary>
            [RepositoryItemInfo("fdf6b9a1-e7f4-4874-b186-c554d5f7f8f8")]
            public virtual RepoItemInfo BAddInfo
            {
                get
                {
                    return _baddInfo;
                }
            }
        }

        /// <summary>
        /// The NouveauDocumentAppFolder folder.
        /// </summary>
        [RepositoryFolder("c48a7c74-d7fa-47ad-ac22-b0d660382dd6")]
        public partial class NouveauDocumentAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _aqxdhoyaInfo;
            RepoItemInfo _elementbokInfo;
            RepoItemInfo _programmedusinageInfo;

            /// <summary>
            /// Creates a new NouveauDocument  folder.
            /// </summary>
            public NouveauDocumentAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NouveauDocument", "/form[@name='NewGalleryForm']", parentFolder, 30000, null, true, "c48a7c74-d7fa-47ad-ac22-b0d660382dd6", "")
            {
                _aqxdhoyaInfo = new RepoItemInfo(this, "AQXDHOYA", "list[@name='DocView']/?/?/rawimage[@id='AQXDHOYA']", "", 30000, null, "b5f51972-779c-4e0c-b04b-d63314b5391b");
                _elementbokInfo = new RepoItemInfo(this, "ElementBOk", "?/?/element[@name='bOk']", "", 30000, null, "38efc64f-5b19-4634-8009-a333dae33e54");
                _programmedusinageInfo = new RepoItemInfo(this, "ProgrammeDusinage", "list[@name='DocView']/?/?/rawtext[@rawtext='Programme d''usinage']", "", 30000, null, "15675ac5-fe16-4ca6-8d72-3d83443e316f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c48a7c74-d7fa-47ad-ac22-b0d660382dd6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c48a7c74-d7fa-47ad-ac22-b0d660382dd6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AQXDHOYA item.
            /// </summary>
            [RepositoryItem("b5f51972-779c-4e0c-b04b-d63314b5391b")]
            public virtual Ranorex.RawImage AQXDHOYA
            {
                get
                {
                    return _aqxdhoyaInfo.CreateAdapter<Ranorex.RawImage>(true);
                }
            }

            /// <summary>
            /// The AQXDHOYA item info.
            /// </summary>
            [RepositoryItemInfo("b5f51972-779c-4e0c-b04b-d63314b5391b")]
            public virtual RepoItemInfo AQXDHOYAInfo
            {
                get
                {
                    return _aqxdhoyaInfo;
                }
            }

            /// <summary>
            /// The ElementBOk item.
            /// </summary>
            [RepositoryItem("38efc64f-5b19-4634-8009-a333dae33e54")]
            public virtual Ranorex.Unknown ElementBOk
            {
                get
                {
                    return _elementbokInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ElementBOk item info.
            /// </summary>
            [RepositoryItemInfo("38efc64f-5b19-4634-8009-a333dae33e54")]
            public virtual RepoItemInfo ElementBOkInfo
            {
                get
                {
                    return _elementbokInfo;
                }
            }

            /// <summary>
            /// The ProgrammeDusinage item.
            /// </summary>
            [RepositoryItem("15675ac5-fe16-4ca6-8d72-3d83443e316f")]
            public virtual Ranorex.RawText ProgrammeDusinage
            {
                get
                {
                    return _programmedusinageInfo.CreateAdapter<Ranorex.RawText>(true);
                }
            }

            /// <summary>
            /// The ProgrammeDusinage item info.
            /// </summary>
            [RepositoryItemInfo("15675ac5-fe16-4ca6-8d72-3d83443e316f")]
            public virtual RepoItemInfo ProgrammeDusinageInfo
            {
                get
                {
                    return _programmedusinageInfo;
                }
            }
        }

        /// <summary>
        /// The ProprietesDunDocumentAppFolder folder.
        /// </summary>
        [RepositoryFolder("877ab74d-7c7d-40e9-b914-ead36713efbe")]
        public partial class ProprietesDunDocumentAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _teditbtnInfo;
            RepoItemInfo _buttonInfo;
            RepoItemInfo _elementbokInfo;
            RepoItemInfo _viewboxInfo;

            /// <summary>
            /// Creates a new ProprietesDunDocument  folder.
            /// </summary>
            public ProprietesDunDocumentAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProprietesDunDocument", "/form[@name='DocItemViewForm']", parentFolder, 30000, null, true, "877ab74d-7c7d-40e9-b914-ead36713efbe", "")
            {
                _teditbtnInfo = new RepoItemInfo(this, "TEditBtn", "container[@name='AdvPanel1']/container[@name='FieldsViewFrame']/?/?/text[@instance='0']", "", 30000, null, "7da211d0-54ab-4572-90a7-aaedde7c7467");
                _buttonInfo = new RepoItemInfo(this, "Button", "container[@name='AdvPanel1']/container[@name='FieldsViewFrame']/container[@name='ViewBox']/text[@instance='6']/?/?/button[@text='...']", "", 30000, null, "4d598daf-f936-4799-a19f-9186578826d6");
                _elementbokInfo = new RepoItemInfo(this, "ElementBOK", "?/?/element[@name='bOK']", "", 30000, null, "665faea3-03f3-4e6f-8421-a646935e0bb3");
                _viewboxInfo = new RepoItemInfo(this, "ViewBox", "container[@name='AdvPanel1']/?/?/container[@name='ViewBox']", "", 30000, null, "3d846682-2a89-4281-a669-aba5fd980f32");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("877ab74d-7c7d-40e9-b914-ead36713efbe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("877ab74d-7c7d-40e9-b914-ead36713efbe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TEditBtn item.
            /// </summary>
            [RepositoryItem("7da211d0-54ab-4572-90a7-aaedde7c7467")]
            public virtual Ranorex.Text TEditBtn
            {
                get
                {
                    return _teditbtnInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TEditBtn item info.
            /// </summary>
            [RepositoryItemInfo("7da211d0-54ab-4572-90a7-aaedde7c7467")]
            public virtual RepoItemInfo TEditBtnInfo
            {
                get
                {
                    return _teditbtnInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("4d598daf-f936-4799-a19f-9186578826d6")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("4d598daf-f936-4799-a19f-9186578826d6")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The ElementBOK item.
            /// </summary>
            [RepositoryItem("665faea3-03f3-4e6f-8421-a646935e0bb3")]
            public virtual Ranorex.Unknown ElementBOK
            {
                get
                {
                    return _elementbokInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ElementBOK item info.
            /// </summary>
            [RepositoryItemInfo("665faea3-03f3-4e6f-8421-a646935e0bb3")]
            public virtual RepoItemInfo ElementBOKInfo
            {
                get
                {
                    return _elementbokInfo;
                }
            }

            /// <summary>
            /// The ViewBox item.
            /// </summary>
            [RepositoryItem("3d846682-2a89-4281-a669-aba5fd980f32")]
            public virtual Ranorex.Container ViewBox
            {
                get
                {
                    return _viewboxInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ViewBox item info.
            /// </summary>
            [RepositoryItemInfo("3d846682-2a89-4281-a669-aba5fd980f32")]
            public virtual RepoItemInfo ViewBoxInfo
            {
                get
                {
                    return _viewboxInfo;
                }
            }
        }

        /// <summary>
        /// The SelectionnerUneCncAppFolder folder.
        /// </summary>
        [RepositoryFolder("44c50f0e-b6db-4e0f-8d27-c1bf16335796")]
        public partial class SelectionnerUneCncAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cnc1Info;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _cnc2Info;
            RepoItemInfo _cnc3Info;

            /// <summary>
            /// Creates a new SelectionnerUneCnc  folder.
            /// </summary>
            public SelectionnerUneCncAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SelectionnerUneCnc", "/form[@name='CncSelectForm']", parentFolder, 30000, null, true, "44c50f0e-b6db-4e0f-8d27-c1bf16335796", "")
            {
                _cnc1Info = new RepoItemInfo(this, "Cnc1", "?/?/listitem[@name='Cnc-1']", "", 30000, null, "388386a5-b551-4841-88d2-7d00919e9f83");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/button[@name='bOk']", "", 30000, null, "91c3993c-b524-4cb8-bb69-b896fecdcedf");
                _cnc2Info = new RepoItemInfo(this, "Cnc2", "?/?/listitem[@name='Cnc-2']", "", 30000, null, "38a4dc9c-0d45-4acb-ac9b-b1cd7648c578");
                _cnc3Info = new RepoItemInfo(this, "Cnc3", "?/?/listitem[@name='Cnc-3']", "", 30000, null, "6b2d0930-9760-4590-971c-3f7733a6508a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("44c50f0e-b6db-4e0f-8d27-c1bf16335796")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("44c50f0e-b6db-4e0f-8d27-c1bf16335796")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cnc1 item.
            /// </summary>
            [RepositoryItem("388386a5-b551-4841-88d2-7d00919e9f83")]
            public virtual Ranorex.ListItem Cnc1
            {
                get
                {
                    return _cnc1Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Cnc1 item info.
            /// </summary>
            [RepositoryItemInfo("388386a5-b551-4841-88d2-7d00919e9f83")]
            public virtual RepoItemInfo Cnc1Info
            {
                get
                {
                    return _cnc1Info;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("91c3993c-b524-4cb8-bb69-b896fecdcedf")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("91c3993c-b524-4cb8-bb69-b896fecdcedf")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Cnc2 item.
            /// </summary>
            [RepositoryItem("38a4dc9c-0d45-4acb-ac9b-b1cd7648c578")]
            public virtual Ranorex.ListItem Cnc2
            {
                get
                {
                    return _cnc2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Cnc2 item info.
            /// </summary>
            [RepositoryItemInfo("38a4dc9c-0d45-4acb-ac9b-b1cd7648c578")]
            public virtual RepoItemInfo Cnc2Info
            {
                get
                {
                    return _cnc2Info;
                }
            }

            /// <summary>
            /// The Cnc3 item.
            /// </summary>
            [RepositoryItem("6b2d0930-9760-4590-971c-3f7733a6508a")]
            public virtual Ranorex.ListItem Cnc3
            {
                get
                {
                    return _cnc3Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Cnc3 item info.
            /// </summary>
            [RepositoryItemInfo("6b2d0930-9760-4590-971c-3f7733a6508a")]
            public virtual RepoItemInfo Cnc3Info
            {
                get
                {
                    return _cnc3Info;
                }
            }
        }

        /// <summary>
        /// The CworkAppFolder folder.
        /// </summary>
        [RepositoryFolder("51906420-ee27-4514-bede-28db9b630134")]
        public partial class CworkAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _voirInfo;

            /// <summary>
            /// Creates a new Cwork  folder.
            /// </summary>
            public CworkAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Cwork", "/contextmenu[@processname='Cwork']", parentFolder, 30000, null, false, "51906420-ee27-4514-bede-28db9b630134", "")
            {
                _voirInfo = new RepoItemInfo(this, "Voir", "?/?/menuitem[@accessiblename='Voir']", "", 30000, null, "9eb5dff7-438a-4917-bf35-962e186276c7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("51906420-ee27-4514-bede-28db9b630134")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("51906420-ee27-4514-bede-28db9b630134")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Voir item.
            /// </summary>
            [RepositoryItem("9eb5dff7-438a-4917-bf35-962e186276c7")]
            public virtual Ranorex.MenuItem Voir
            {
                get
                {
                    return _voirInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Voir item info.
            /// </summary>
            [RepositoryItemInfo("9eb5dff7-438a-4917-bf35-962e186276c7")]
            public virtual RepoItemInfo VoirInfo
            {
                get
                {
                    return _voirInfo;
                }
            }
        }

        /// <summary>
        /// The SauvegardeDesModificationsAppFolder folder.
        /// </summary>
        [RepositoryFolder("4ceec5ee-6e38-4bc1-8253-efc4a14126d3")]
        public partial class SauvegardeDesModificationsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _annulerInfo;

            /// <summary>
            /// Creates a new SauvegardeDesModifications  folder.
            /// </summary>
            public SauvegardeDesModificationsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SauvegardeDesModifications", "/form[@title>'Sauvegarde des modificati']", parentFolder, 30000, null, true, "4ceec5ee-6e38-4bc1-8253-efc4a14126d3", "")
            {
                _annulerInfo = new RepoItemInfo(this, "Annuler", "button[@text='Annuler']", "", 30000, null, "ada9ddf9-8ffd-4ed6-b9db-22858402015a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4ceec5ee-6e38-4bc1-8253-efc4a14126d3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4ceec5ee-6e38-4bc1-8253-efc4a14126d3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Annuler item.
            /// </summary>
            [RepositoryItem("ada9ddf9-8ffd-4ed6-b9db-22858402015a")]
            public virtual Ranorex.Button Annuler
            {
                get
                {
                    return _annulerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Annuler item info.
            /// </summary>
            [RepositoryItemInfo("ada9ddf9-8ffd-4ed6-b9db-22858402015a")]
            public virtual RepoItemInfo AnnulerInfo
            {
                get
                {
                    return _annulerInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
