///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CworkTestLib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddProdState recording.
    /// </summary>
    [TestModule("1e56b23a-0e98-4eb4-a898-5754bbdf8aae", ModuleType.Recording, 1)]
    public partial class AddProdState : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CworkTestLibRepository repository.
        /// </summary>
        public static CworkTestLibRepository repo = CworkTestLibRepository.Instance;

        static AddProdState instance = new AddProdState();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddProdState()
        {
            StateName = "State1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddProdState Instance
        {
            get { return instance; }
        }

#region Variables

        string _StateName;

        /// <summary>
        /// Gets or sets the value of variable StateName.
        /// </summary>
        [TestVariable("a9a94f21-3b21-4632-b008-cd7f637e2486")]
        public string StateName
        {
            get { return _StateName; }
            set { _StateName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.CWork202195.MenuItemOutils' at 18;4.", repo.CworkMainForm.CWork202195.MenuItemOutilsInfo, new RecordItemIndex(0));
            //repo.CworkMainForm.CWork202195.MenuItemOutils.Click("18;4");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cwork2024983DEV.MenuItemOutils' at Center.", repo.Cwork2024983DEV.MenuItemOutilsInfo, new RecordItemIndex(1));
            repo.Cwork2024983DEV.MenuItemOutils.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.Cwork.MenuItem1' at 67;11.", repo.CworkMainForm.Cwork.MenuItem1Info, new RecordItemIndex(2));
            repo.CworkMainForm.Cwork.MenuItem1.Click("67;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OptionsDeProduction.Ajouter' at 39;10.", repo.OptionsDeProduction.AjouterInfo, new RecordItemIndex(3));
            repo.OptionsDeProduction.Ajouter.Click("39;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AjoutDunEtat.EdNameNewState' at 20;10.", repo.AjoutDunEtat.EdNameNewStateInfo, new RecordItemIndex(4));
            repo.AjoutDunEtat.EdNameNewState.Click("20;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$StateName' with focus on 'AjoutDunEtat.EdNameNewState'.", repo.AjoutDunEtat.EdNameNewStateInfo, new RecordItemIndex(5));
            repo.AjoutDunEtat.EdNameNewState.PressKeys(StateName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AjoutDunEtat.Valider' at 44;6.", repo.AjoutDunEtat.ValiderInfo, new RecordItemIndex(6));
            repo.AjoutDunEtat.Valider.Click("44;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OptionsDeProduction.Valider' at 37;8.", repo.OptionsDeProduction.ValiderInfo, new RecordItemIndex(7));
            repo.OptionsDeProduction.Valider.Click("37;8");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Informations.ButtonOui' at 31;5.", repo.Informations.ButtonOuiInfo, new RecordItemIndex(8));
            //repo.Informations.ButtonOui.Click("31;5");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormHash32770.ButtonOK' at 40;11.", repo.FormHash32770.ButtonOKInfo, new RecordItemIndex(9));
            repo.FormHash32770.ButtonOK.Click("40;11");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
