///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CworkTestLib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CallSendAsyncProgAPIWithWrongParam recording.
    /// </summary>
    [TestModule("e25bfe9a-107f-4e26-8007-365170ab9212", ModuleType.Recording, 1)]
    public partial class CallSendAsyncProgAPIWithWrongParam : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_8_3Repository repository.
        /// </summary>
        public static Sprint_9_8_3Repository repo = Sprint_9_8_3Repository.Instance;

        static CallSendAsyncProgAPIWithWrongParam instance = new CallSendAsyncProgAPIWithWrongParam();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CallSendAsyncProgAPIWithWrongParam()
        {
            varCncId = "0";
            varDocumentName = "";
            varDocExtension = "";
            varSourceFolder = "";
            varUser = "";
            varpsw = "";
            varExpectedRes = "";
            varDestinationFolder = "";
            varDestinationFolderMode = "";
            varOverride = "False";
            varWaitBeforQuerySendStatus = "0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CallSendAsyncProgAPIWithWrongParam Instance
        {
            get { return instance; }
        }

#region Variables

        string _varCncId;

        /// <summary>
        /// Gets or sets the value of variable varCncId.
        /// </summary>
        [TestVariable("6df82a5f-c678-4e0b-90a6-8f6c6bd397d5")]
        public string varCncId
        {
            get { return _varCncId; }
            set { _varCncId = value; }
        }

        string _varDocumentName;

        /// <summary>
        /// Gets or sets the value of variable varDocumentName.
        /// </summary>
        [TestVariable("3ef57d7e-a6f8-4f0d-976c-3babd38e49c8")]
        public string varDocumentName
        {
            get { return _varDocumentName; }
            set { _varDocumentName = value; }
        }

        string _varDocExtension;

        /// <summary>
        /// Gets or sets the value of variable varDocExtension.
        /// </summary>
        [TestVariable("a140c2cc-a9e1-46d1-8774-a43977e3e363")]
        public string varDocExtension
        {
            get { return _varDocExtension; }
            set { _varDocExtension = value; }
        }

        string _varSourceFolder;

        /// <summary>
        /// Gets or sets the value of variable varSourceFolder.
        /// </summary>
        [TestVariable("ad256dd4-d598-4351-8b1f-77976b0c4571")]
        public string varSourceFolder
        {
            get { return _varSourceFolder; }
            set { _varSourceFolder = value; }
        }

        string _varUser;

        /// <summary>
        /// Gets or sets the value of variable varUser.
        /// </summary>
        [TestVariable("a20ff59d-231d-43e8-b0dd-3c5012eacb6f")]
        public string varUser
        {
            get { return _varUser; }
            set { _varUser = value; }
        }

        string _varpsw;

        /// <summary>
        /// Gets or sets the value of variable varpsw.
        /// </summary>
        [TestVariable("f20e38a9-bb2e-48ca-bcf7-faeebaef5f7d")]
        public string varpsw
        {
            get { return _varpsw; }
            set { _varpsw = value; }
        }

        string _varExpectedRes;

        /// <summary>
        /// Gets or sets the value of variable varExpectedRes.
        /// </summary>
        [TestVariable("73c9f46b-858f-4939-a962-7655647db1e1")]
        public string varExpectedRes
        {
            get { return _varExpectedRes; }
            set { _varExpectedRes = value; }
        }

        string _varDestinationFolder;

        /// <summary>
        /// Gets or sets the value of variable varDestinationFolder.
        /// </summary>
        [TestVariable("a28518c1-2f73-4ad3-87ce-c13dc07228fd")]
        public string varDestinationFolder
        {
            get { return _varDestinationFolder; }
            set { _varDestinationFolder = value; }
        }

        string _varDestinationFolderMode;

        /// <summary>
        /// Gets or sets the value of variable varDestinationFolderMode.
        /// </summary>
        [TestVariable("82f3f0db-dd5e-42d9-950a-3bd27cff1f1b")]
        public string varDestinationFolderMode
        {
            get { return _varDestinationFolderMode; }
            set { _varDestinationFolderMode = value; }
        }

        string _varOverride;

        /// <summary>
        /// Gets or sets the value of variable varOverride.
        /// </summary>
        [TestVariable("574400b2-a095-4ded-a451-5363cd54123e")]
        public string varOverride
        {
            get { return _varOverride; }
            set { _varOverride = value; }
        }

        string _varWaitBeforQuerySendStatus;

        /// <summary>
        /// Gets or sets the value of variable varWaitBeforQuerySendStatus.
        /// </summary>
        [TestVariable("8b02ddb1-39e0-48ec-85df-d23529475c70")]
        public string varWaitBeforQuerySendStatus
        {
            get { return _varWaitBeforQuerySendStatus; }
            set { _varWaitBeforQuerySendStatus = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            CallSendAsyncProgApiCodeWrongParam(ValueConverter.ArgumentFromString<int>("CncId", varCncId), varDocumentName, varDocExtension, varSourceFolder, varUser, varpsw, varExpectedRes, varDestinationFolder, varDestinationFolderMode, ValueConverter.ArgumentFromString<bool>("Override", varOverride), ValueConverter.ArgumentFromString<int>("WaitBeforQuerySendStatus", varWaitBeforQuerySendStatus));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
