///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CworkTestLib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckFileTnc recording.
    /// </summary>
    [TestModule("5bc44fd9-c8d9-4287-9ccb-1003a9d67472", ModuleType.Recording, 1)]
    public partial class CheckFileTnc : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CworkTestLibRepository repository.
        /// </summary>
        public static CworkTestLibRepository repo = CworkTestLibRepository.Instance;

        static CheckFileTnc instance = new CheckFileTnc();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckFileTnc()
        {
            varGenParameters = "";
            varFileToScanPath = "";
            varFileNametToFind = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckFileTnc Instance
        {
            get { return instance; }
        }

#region Variables

        string _varGenParameters;

        /// <summary>
        /// Gets or sets the value of variable varGenParameters.
        /// </summary>
        [TestVariable("3fd10ece-4c9b-44c9-a849-228d9d0c5b49")]
        public string varGenParameters
        {
            get { return _varGenParameters; }
            set { _varGenParameters = value; }
        }

        string _varFileToScanPath;

        /// <summary>
        /// Gets or sets the value of variable varFileToScanPath.
        /// </summary>
        [TestVariable("ee66df9f-1f97-4ab8-9657-be7603c23663")]
        public string varFileToScanPath
        {
            get { return _varFileToScanPath; }
            set { _varFileToScanPath = value; }
        }

        string _varFileNametToFind;

        /// <summary>
        /// Gets or sets the value of variable varFileNametToFind.
        /// </summary>
        [TestVariable("6edbfd8c-579d-428c-8d52-83b870365d38")]
        public string varFileNametToFind
        {
            get { return _varFileNametToFind; }
            set { _varFileNametToFind = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollection.RunProgramAndWait("TestPrep\\GenerateFileResultOfCheckFileInTnc.bat", varGenParameters, ValueConverter.ArgumentFromString<int>("waitSeconds", "180"));
            Delay.Milliseconds(0);
            
            UserCodeCollectionFileMng.CheckIfFileNotContainText(varFileToScanPath, "Error");
            Delay.Milliseconds(0);
            
            Ranorex.AutomationHelpers.UserCodeCollections.FileLibrary.ValidateFileContainsText(varFileToScanPath, varFileNametToFind);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
