///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CworkTestLib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckTextInCworkLog recording.
    /// </summary>
    [TestModule("de05138e-28c0-4ec1-a745-417c12e217e3", ModuleType.Recording, 1)]
    public partial class CheckTextInCworkLog : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CworkTestLibRepository repository.
        /// </summary>
        public static CworkTestLibRepository repo = CworkTestLibRepository.Instance;

        static CheckTextInCworkLog instance = new CheckTextInCworkLog();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckTextInCworkLog()
        {
            varText = "";
            varColumn = "4";
            varRow = "3";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckTextInCworkLog Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varText.
        /// </summary>
        [TestVariable("fe18b448-3455-4475-90d2-314ec43c811d")]
        public string varText
        {
            get { return repo.varText; }
            set { repo.varText = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varColumn.
        /// </summary>
        [TestVariable("22a40be0-730d-4d0c-856d-aaae0e4a2487")]
        public string varColumn
        {
            get { return repo.varColumn; }
            set { repo.varColumn = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRow.
        /// </summary>
        [TestVariable("7ef62aae-2363-4621-989b-d369f530fb98")]
        public string varRow
        {
            get { return repo.varRow; }
            set { repo.varRow = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Column=$varColumn) on item 'CworkMainForm.CWork202195.PreparationDePrg1'.", repo.CworkMainForm.CWork202195.PreparationDePrg1Info, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.CworkMainForm.CWork202195.PreparationDePrg1Info, "Column", varColumn);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (RawText=$varText) on item 'CworkMainForm.CWork202195.PreparationDePrg1'.", repo.CworkMainForm.CWork202195.PreparationDePrg1Info, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.CworkMainForm.CWork202195.PreparationDePrg1Info, "RawText", varText);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Row=$varRow) on item 'CworkMainForm.CWork202195.PreparationDePrg1'.", repo.CworkMainForm.CWork202195.PreparationDePrg1Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.CworkMainForm.CWork202195.PreparationDePrg1Info, "Row", varRow);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
