///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CworkTestLib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckFileInFocasCnc recording.
    /// </summary>
    [TestModule("7d3caf0f-1cc8-4da7-8976-91cc2b944710", ModuleType.Recording, 1)]
    public partial class CheckFileInFocasCnc : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CworkTestLibRepository repository.
        /// </summary>
        public static CworkTestLibRepository repo = CworkTestLibRepository.Instance;

        static CheckFileInFocasCnc instance = new CheckFileInFocasCnc();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckFileInFocasCnc()
        {
            varPath = "//CNC_MEM/TestCworkAuto/";
            varFileName = "prg1";
            varCncIp = "10.001.000.187";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckFileInFocasCnc Instance
        {
            get { return instance; }
        }

#region Variables

        string _varPath;

        /// <summary>
        /// Gets or sets the value of variable varPath.
        /// </summary>
        [TestVariable("f93aa3fc-a5a0-4da8-8df9-6856d175d90f")]
        public string varPath
        {
            get { return _varPath; }
            set { _varPath = value; }
        }

        string _varFileName;

        /// <summary>
        /// Gets or sets the value of variable varFileName.
        /// </summary>
        [TestVariable("1f08703f-ace8-4745-9fbd-d276443726c9")]
        public string varFileName
        {
            get { return _varFileName; }
            set { _varFileName = value; }
        }

        string _varCncIp;

        /// <summary>
        /// Gets or sets the value of variable varCncIp.
        /// </summary>
        [TestVariable("cc0a8dcf-fa20-48c8-8dd4-d3e75c3df29c")]
        public string varCncIp
        {
            get { return _varCncIp; }
            set { _varCncIp = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollectionFocas.CheckIfFileExistInCnc(varPath, varFileName, varCncIp);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
