///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CworkTestLib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConfigCncAsSMBClient recording.
    /// </summary>
    [TestModule("06f71a5f-cf3f-4220-983c-55cdb2d73d00", ModuleType.Recording, 1)]
    public partial class ConfigCncAsSMBClient : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CworkTestLibRepository repository.
        /// </summary>
        public static CworkTestLibRepository repo = CworkTestLibRepository.Instance;

        static ConfigCncAsSMBClient instance = new ConfigCncAsSMBClient();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConfigCncAsSMBClient()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConfigCncAsSMBClient Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.Cnc1' at Center.", repo.CworkMainForm1.Cnc1Info, new RecordItemIndex(0));
            repo.CworkMainForm1.Cnc1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.CWork202195.BProperty' at Center.", repo.CworkMainForm.CWork202195.BPropertyInfo, new RecordItemIndex(1));
            repo.CworkMainForm.CWork202195.BProperty.Click();
            Delay.Milliseconds(0);
            
            // Choix du type deconfiguration à Fanuc RS232
            Report.Log(ReportLevel.Info, "Mouse", "Choix du type deconfiguration à Fanuc RS232\r\nMouse Left Click item 'ChoixDuneConfiguration.ListItemDefaultFanucRS232' at 54;6.", repo.ChoixDuneConfiguration.ListItemDefaultFanucRS232Info, new RecordItemIndex(2));
            repo.ChoixDuneConfiguration.ListItemDefaultFanucRS232.Click("54;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ChoixDuneConfiguration.ElementBOk' at 54;16.", repo.ChoixDuneConfiguration.ElementBOkInfo, new RecordItemIndex(3));
            repo.ChoixDuneConfiguration.ElementBOk.Click("54;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.General' at 25;9.", repo.ProprietesPourCnc1.GeneralInfo, new RecordItemIndex(4));
            repo.ProprietesPourCnc1.General.Click("25;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.SMBClient' at 27;6.", repo.ProprietesPourCnc1.SMBClientInfo, new RecordItemIndex(5));
            repo.ProprietesPourCnc1.SMBClient.Click("27;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.SMBClient1' at 31;1.", repo.ProprietesPourCnc1.SMBClient1Info, new RecordItemIndex(6));
            repo.ProprietesPourCnc1.SMBClient1.Click("31;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.EdSMBCli' at 38;15.", repo.ProprietesPourCnc1.EdSMBCliInfo, new RecordItemIndex(7));
            repo.ProprietesPourCnc1.EdSMBCli.Click("38;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\CworkTestAuto\\SMB\\CNC1\\Decharg\\' with focus on 'ProprietesPourCnc1.EdSMBCli'.", repo.ProprietesPourCnc1.EdSMBCliInfo, new RecordItemIndex(8));
            repo.ProprietesPourCnc1.EdSMBCli.PressKeys("C:\\CworkTestAuto\\SMB\\CNC1\\Decharg\\");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.ButtonAppliquer' at 46;10.", repo.ProprietesPourCnc1.ButtonAppliquerInfo, new RecordItemIndex(9));
            repo.ProprietesPourCnc1.ButtonAppliquer.Click("46;10");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
