///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CworkTestLib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConfigCncAsFanukSMB recording.
    /// </summary>
    [TestModule("3ebe42dc-4084-45bc-98b4-33e61971b003", ModuleType.Recording, 1)]
    public partial class ConfigCncAsFanukSMB : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CworkTestLibRepository repository.
        /// </summary>
        public static CworkTestLibRepository repo = CworkTestLibRepository.Instance;

        static ConfigCncAsFanukSMB instance = new ConfigCncAsFanukSMB();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConfigCncAsFanukSMB()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConfigCncAsFanukSMB Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.Cnc1' at Center.", repo.CworkMainForm1.Cnc1Info, new RecordItemIndex(0));
            repo.CworkMainForm1.Cnc1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.CWork202195.BProperty' at Center.", repo.CworkMainForm.CWork202195.BPropertyInfo, new RecordItemIndex(1));
            repo.CworkMainForm.CWork202195.BProperty.Click();
            Delay.Milliseconds(0);
            
            // Choix du type deconfiguration à Fanuc RS232
            Report.Log(ReportLevel.Info, "Mouse", "Choix du type deconfiguration à Fanuc RS232\r\nMouse Left Click item 'ChoixDuneConfiguration.ListItemDefaultFanucRS232' at 54;6.", repo.ChoixDuneConfiguration.ListItemDefaultFanucRS232Info, new RecordItemIndex(2));
            repo.ChoixDuneConfiguration.ListItemDefaultFanucRS232.Click("54;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ChoixDuneConfiguration.ElementBOk' at 54;16.", repo.ChoixDuneConfiguration.ElementBOkInfo, new RecordItemIndex(3));
            repo.ChoixDuneConfiguration.ElementBOk.Click("54;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.General' at 20;6.", repo.ProprietesPourCnc1.GeneralInfo, new RecordItemIndex(4));
            repo.ProprietesPourCnc1.General.Click("20;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.RawTextSMB' at 12;5.", repo.ProprietesPourCnc1.RawTextSMBInfo, new RecordItemIndex(5));
            repo.ProprietesPourCnc1.RawTextSMB.Click("12;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.TreeItemSMB' at 15;9.", repo.ProprietesPourCnc1.TreeItemSMBInfo, new RecordItemIndex(6));
            repo.ProprietesPourCnc1.TreeItemSMB.Click("15;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.EdMirrorOut' at 18;11.", repo.ProprietesPourCnc1.EdMirrorOutInfo, new RecordItemIndex(7));
            repo.ProprietesPourCnc1.EdMirrorOut.Click("18;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.EdMirrorOut' at 11;11.", repo.ProprietesPourCnc1.EdMirrorOutInfo, new RecordItemIndex(8));
            repo.ProprietesPourCnc1.EdMirrorOut.Click("11;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\CworkTestAuto\\SMB\\CNC1\\Charg\\' with focus on 'ProprietesPourCnc1.EdMirrorOut'.", repo.ProprietesPourCnc1.EdMirrorOutInfo, new RecordItemIndex(9));
            repo.ProprietesPourCnc1.EdMirrorOut.PressKeys("C:\\CworkTestAuto\\SMB\\CNC1\\Charg\\");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.EdMirrorIn' at 14;9.", repo.ProprietesPourCnc1.EdMirrorInInfo, new RecordItemIndex(10));
            repo.ProprietesPourCnc1.EdMirrorIn.Click("14;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\CworkTestAuto\\SMB\\CNC1\\Decharg\\' with focus on 'ProprietesPourCnc1.EdMirrorIn'.", repo.ProprietesPourCnc1.EdMirrorInInfo, new RecordItemIndex(11));
            repo.ProprietesPourCnc1.EdMirrorIn.PressKeys("C:\\CworkTestAuto\\SMB\\CNC1\\Decharg\\");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.EdSmbDeleteDelay' at 27;9.", repo.ProprietesPourCnc1.EdSmbDeleteDelayInfo, new RecordItemIndex(12));
            repo.ProprietesPourCnc1.EdSmbDeleteDelay.Click("27;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'ProprietesPourCnc1.EdSmbDeleteDelay'.", repo.ProprietesPourCnc1.EdSmbDeleteDelayInfo, new RecordItemIndex(13));
            Keyboard.PrepareFocus(repo.ProprietesPourCnc1.EdSmbDeleteDelay);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 16, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'ProprietesPourCnc1.EdSmbDeleteDelay'.", repo.ProprietesPourCnc1.EdSmbDeleteDelayInfo, new RecordItemIndex(14));
            repo.ProprietesPourCnc1.EdSmbDeleteDelay.PressKeys("{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '10' with focus on 'ProprietesPourCnc1.EdSmbDeleteDelay'.", repo.ProprietesPourCnc1.EdSmbDeleteDelayInfo, new RecordItemIndex(15));
            repo.ProprietesPourCnc1.EdSmbDeleteDelay.PressKeys("10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.DepuisLePupitre' at 57;6.", repo.ProprietesPourCnc1.DepuisLePupitreInfo, new RecordItemIndex(16));
            repo.ProprietesPourCnc1.DepuisLePupitre.Click("57;6");
            Delay.Milliseconds(0);
            
            // Configuration capture repertoir
            Report.Log(ReportLevel.Info, "Mouse", "Configuration capture repertoir\r\nMouse Left Click item 'ProprietesPourCnc1.OptParam2' at 13;9.", repo.ProprietesPourCnc1.OptParam2Info, new RecordItemIndex(17));
            repo.ProprietesPourCnc1.OptParam2.Click("13;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '({LControlKey down}{RMenu down}{D0}{LControlKey up}{LControlKey up}{RMenu up})' with focus on 'ProprietesPourCnc1.OptParam2'.", repo.ProprietesPourCnc1.OptParam2Info, new RecordItemIndex(18));
            repo.ProprietesPourCnc1.OptParam2.PressKeys("({LControlKey down}{RMenu down}{D0}{LControlKey up}{LControlKey up}{RMenu up})");
            Delay.Milliseconds(0);
            
            // on saisie (@)
            Report.Log(ReportLevel.Info, "Mouse", "on saisie (@)\r\nMouse Left Click item 'ProprietesPourCnc1.ButtonAppliquer' at 46;10.", repo.ProprietesPourCnc1.ButtonAppliquerInfo, new RecordItemIndex(19));
            repo.ProprietesPourCnc1.ButtonAppliquer.Click("46;10");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
