///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CworkTestLib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ImportPrgFromFaoFolder2 recording.
    /// </summary>
    [TestModule("2e2f90b3-3b72-4687-a20b-21b102ab7134", ModuleType.Recording, 1)]
    public partial class ImportPrgFromFaoFolder2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CworkTestLibRepository repository.
        /// </summary>
        public static CworkTestLibRepository repo = CworkTestLibRepository.Instance;

        static ImportPrgFromFaoFolder2 instance = new ImportPrgFromFaoFolder2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ImportPrgFromFaoFolder2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ImportPrgFromFaoFolder2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                //repo.Confirmer.OuiPourTout.Click("68;10");
                //Delay.Milliseconds(0);
            } catch(Exception) {  }
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.CWork202195.MenuItemFichier' at 29;11.", repo.CworkMainForm.CWork202195.MenuItemFichierInfo, new RecordItemIndex(1));
            //repo.CworkMainForm.CWork202195.MenuItemFichier.Click("29;11");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cwork2024983DEV.MenuItemFichier' at Center.", repo.Cwork2024983DEV.MenuItemFichierInfo, new RecordItemIndex(2));
            repo.Cwork2024983DEV.MenuItemFichier.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.Cwork.MenuItem1' at 64;16.", repo.CworkMainForm.Cwork.MenuItem1Info, new RecordItemIndex(3));
            repo.CworkMainForm.Cwork.MenuItem1.Click("64;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ImportationDunDocumentOuDunDossier.OptStatus' at 157;15.", repo.ImportationDunDocumentOuDunDossier.OptStatusInfo, new RecordItemIndex(4));
            repo.ImportationDunDocumentOuDunDossier.OptStatus.Click("157;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.VALIDE' at 19;2.", repo.List1000.VALIDEInfo, new RecordItemIndex(5));
            repo.List1000.VALIDE.Click("19;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ImportationDunDocumentOuDunDossier.OptImportFolder' at 17;11.", repo.ImportationDunDocumentOuDunDossier.OptImportFolderInfo, new RecordItemIndex(6));
            repo.ImportationDunDocumentOuDunDossier.OptImportFolder.Click("17;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\CworkTestAuto\\ImportFAO' with focus on 'ImportationDunDocumentOuDunDossier.OptImportFolder'.", repo.ImportationDunDocumentOuDunDossier.OptImportFolderInfo, new RecordItemIndex(7));
            repo.ImportationDunDocumentOuDunDossier.OptImportFolder.PressKeys("C:\\CworkTestAuto\\ImportFAO");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ImportationDunDocumentOuDunDossier.Button1' at 8;12.", repo.ImportationDunDocumentOuDunDossier.Button1Info, new RecordItemIndex(8));
            repo.ImportationDunDocumentOuDunDossier.Button1.Click("8;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SelectionnerUneCnc.Cnc1' at 15;8.", repo.SelectionnerUneCnc.Cnc1Info, new RecordItemIndex(9));
            repo.SelectionnerUneCnc.Cnc1.Click("15;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SelectionnerUneCnc.ButtonOK' at 44;13.", repo.SelectionnerUneCnc.ButtonOKInfo, new RecordItemIndex(10));
            repo.SelectionnerUneCnc.ButtonOK.Click("44;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ImportationDunDocumentOuDunDossier.ElementBOk' at 92;14.", repo.ImportationDunDocumentOuDunDossier.ElementBOkInfo, new RecordItemIndex(11));
            repo.ImportationDunDocumentOuDunDossier.ElementBOk.Click("92;14");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Confirmer.OuiPourTout' at Center.", repo.Confirmer.OuiPourToutInfo, new RecordItemIndex(12));
            //repo.Confirmer.OuiPourTout.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Confirmer.YesToAll' at Center.", repo.Confirmer.YesToAllInfo, new RecordItemIndex(13));
            repo.Confirmer.YesToAll.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 4m to not exist. Associated repository item: 'ImportationDunDocumentOuDunDossier'", repo.ImportationDunDocumentOuDunDossier.SelfInfo, new ActionTimeout(240000), new RecordItemIndex(14));
            repo.ImportationDunDocumentOuDunDossier.SelfInfo.WaitForNotExists(240000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.CWork202195.StationsTiles' at 671;296.", repo.CworkMainForm.CWork202195.StationsTilesInfo, new RecordItemIndex(15));
            repo.CworkMainForm.CWork202195.StationsTiles.Click("671;296");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
