///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CworkTestLib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Import1PrgFromFaoFolder recording.
    /// </summary>
    [TestModule("db7edd9b-cdbb-4785-b504-564b6e9ab41d", ModuleType.Recording, 1)]
    public partial class Import1PrgFromFaoFolder : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CworkTestLibRepository repository.
        /// </summary>
        public static CworkTestLibRepository repo = CworkTestLibRepository.Instance;

        static Import1PrgFromFaoFolder instance = new Import1PrgFromFaoFolder();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Import1PrgFromFaoFolder()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Import1PrgFromFaoFolder Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.CWork202195.StationsTiles' at 690;108.", repo.CworkMainForm.CWork202195.StationsTilesInfo, new RecordItemIndex(0));
            repo.CworkMainForm.CWork202195.StationsTiles.Click("690;108");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.CWork202195.MenuItemFichier' at 29;11.", repo.CworkMainForm.CWork202195.MenuItemFichierInfo, new RecordItemIndex(1));
            //repo.CworkMainForm.CWork202195.MenuItemFichier.Click("29;11");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cwork2024983DEV.MenuItemFichier' at Center.", repo.Cwork2024983DEV.MenuItemFichierInfo, new RecordItemIndex(2));
            repo.Cwork2024983DEV.MenuItemFichier.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.Cwork.MenuItem1' at 64;16.", repo.CworkMainForm.Cwork.MenuItem1Info, new RecordItemIndex(3));
            repo.CworkMainForm.Cwork.MenuItem1.Click("64;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ImportationDunDocumentOuDunDossier.OptFilename' at 17;11.", repo.ImportationDunDocumentOuDunDossier.OptFilenameInfo, new RecordItemIndex(4));
            repo.ImportationDunDocumentOuDunDossier.OptFilename.Click("17;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\CworkTestAuto\\ImportFAO\\png1.cnc' with focus on 'ImportationDunDocumentOuDunDossier.OptFilename'.", repo.ImportationDunDocumentOuDunDossier.OptFilenameInfo, new RecordItemIndex(5));
            repo.ImportationDunDocumentOuDunDossier.OptFilename.PressKeys("C:\\CworkTestAuto\\ImportFAO\\png1.cnc");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ImportationDunDocumentOuDunDossier.Button1' at 8;12.", repo.ImportationDunDocumentOuDunDossier.Button1Info, new RecordItemIndex(6));
            repo.ImportationDunDocumentOuDunDossier.Button1.Click("8;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SelectionnerUneCnc.Cnc1' at 15;8.", repo.SelectionnerUneCnc.Cnc1Info, new RecordItemIndex(7));
            repo.SelectionnerUneCnc.Cnc1.Click("15;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SelectionnerUneCnc.ButtonOK' at 44;13.", repo.SelectionnerUneCnc.ButtonOKInfo, new RecordItemIndex(8));
            repo.SelectionnerUneCnc.ButtonOK.Click("44;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ImportationDunDocumentOuDunDossier.ElementBOk' at 92;14.", repo.ImportationDunDocumentOuDunDossier.ElementBOkInfo, new RecordItemIndex(9));
            repo.ImportationDunDocumentOuDunDossier.ElementBOk.Click("92;14");
            Delay.Milliseconds(0);
            
            try {
                repo.Confirmer.OuiPourTout.Click("68;10");
                Delay.Milliseconds(0);
            } catch(Exception) {  }
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 4m to not exist. Associated repository item: 'ImportationDunDocumentOuDunDossier'", repo.ImportationDunDocumentOuDunDossier.SelfInfo, new ActionTimeout(240000), new RecordItemIndex(11));
            repo.ImportationDunDocumentOuDunDossier.SelfInfo.WaitForNotExists(240000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
