///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CworkTestLib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NewWorkingDirServerAndAccessDncProd recording.
    /// </summary>
    [TestModule("f168876e-186a-4c0f-ae20-d7f838a62ba4", ModuleType.Recording, 1)]
    public partial class NewWorkingDirServerAndAccess : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CworkTestLibRepository repository.
        /// </summary>
        public static CworkTestLibRepository repo = CworkTestLibRepository.Instance;

        static NewWorkingDirServerAndAccess instance = new NewWorkingDirServerAndAccess();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NewWorkingDirServerAndAccess()
        {
            AppToRun = "C:\\Program Files (x86)\\Smcom Software\\Cwork\\bin\\Cwork.exe";
            AppWorkingDir = "C:\\SMCOM\\Source\\Cwork80\\bin";
            CworkWorkingDir = "C:\\CworkTestAuto";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NewWorkingDirServerAndAccess Instance
        {
            get { return instance; }
        }

#region Variables

        string _AppToRun;

        /// <summary>
        /// Gets or sets the value of variable AppToRun.
        /// </summary>
        [TestVariable("28ac914a-b0c3-49bd-948c-4cc450f16994")]
        public string AppToRun
        {
            get { return _AppToRun; }
            set { _AppToRun = value; }
        }

        string _AppWorkingDir;

        /// <summary>
        /// Gets or sets the value of variable AppWorkingDir.
        /// </summary>
        [TestVariable("e3c211de-2c33-4885-a1d0-f8afe679ae1f")]
        public string AppWorkingDir
        {
            get { return _AppWorkingDir; }
            set { _AppWorkingDir = value; }
        }

        string _CworkWorkingDir;

        /// <summary>
        /// Gets or sets the value of variable CworkWorkingDir.
        /// </summary>
        [TestVariable("c44878fe-5ee8-43fd-a3a7-133ccb3a554f")]
        public string CworkWorkingDir
        {
            get { return _CworkWorkingDir; }
            set { _CworkWorkingDir = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\Smcom Software\\Cwork\\bin\\Cwork.exe' with arguments '/WIZARD' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\Smcom Software\\Cwork\\bin\\Cwork.exe", "/WIZARD", AppWorkingDir, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptDataDir' at Center.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptDataDirInfo, new RecordItemIndex(1));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptDataDir.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptDataDir'.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptDataDirInfo, new RecordItemIndex(2));
            Keyboard.PrepareFocus(repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptDataDir);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CworkWorkingDir' with focus on 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptDataDir'.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptDataDirInfo, new RecordItemIndex(3));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptDataDir.EnsureVisible();
            Keyboard.Press(CworkWorkingDir);
            Delay.Milliseconds(0);
            
            // wait empty compagny name
            Report.Log(ReportLevel.Info, "Delay", "wait empty compagny name\r\nWaiting for 5s.", new RecordItemIndex(4));
            Delay.Duration(5000, false);
            
            // Enter compagny name
            Report.Log(ReportLevel.Info, "Keyboard", "Enter compagny name\r\nKey sequence 'Smcom' with focus on 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptSociety'.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptSocietyInfo, new RecordItemIndex(5));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptSociety.PressKeys("Smcom");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptPartnerID' at 36;14.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptPartnerIDInfo, new RecordItemIndex(6));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptPartnerID.Click("36;14");
            Delay.Milliseconds(0);
            
            //Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Smcom') on item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptSociety1'.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptSociety1Info, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.OptSociety1Info, "Text", "Smcom");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext' at Center.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(9));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Selectionner la fonction de votre ordinateur') on item 'CworkAssitantConfig.StartWizardForm.SelectionnerLaFonctionDeVotreOrdina'.", repo.CworkAssitantConfig.StartWizardForm.SelectionnerLaFonctionDeVotreOrdinaInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.CworkAssitantConfig.StartWizardForm.SelectionnerLaFonctionDeVotreOrdinaInfo, "Text", "Selectionner la fonction de votre ordinateur");
            Delay.Milliseconds(100);
            
            // Select Server
            Report.Log(ReportLevel.Info, "Mouse", "Select Server\r\nMouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BtnServeur' at Center.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BtnServeurInfo, new RecordItemIndex(11));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BtnServeur.Click();
            Delay.Milliseconds(0);
            
            // Server selected
            Report.Log(ReportLevel.Info, "Validation", "Server selected\r\nValidating Exists on item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext'.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(12));
            Validate.Exists(repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext' at Center.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(13));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext.Click();
            Delay.Milliseconds(0);
            
            // Information server displayed
            Report.Log(ReportLevel.Info, "Validation", "Information server displayed\r\nValidating Exists on item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext'.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(14));
            Validate.Exists(repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext' at Center.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(15));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext.Click();
            Delay.Milliseconds(0);
            
            // Choix base displayed
            Report.Log(ReportLevel.Info, "Validation", "Choix base displayed\r\nValidating Exists on item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext'.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(16));
            Validate.Exists(repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext' at Center.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(17));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext.Click();
            Delay.Milliseconds(0);
            
            // Choix attelier
            Report.Log(ReportLevel.Info, "Mouse", "Choix attelier\r\nMouse Left Click item 'CworkAssitantConfig.StartWizardForm.BAddSupervision' at Center.", repo.CworkAssitantConfig.StartWizardForm.BAddSupervisionInfo, new RecordItemIndex(18));
            repo.CworkAssitantConfig.StartWizardForm.BAddSupervision.Click();
            Delay.Milliseconds(0);
            
            // Enter name of workshop
            Report.Log(ReportLevel.Info, "Keyboard", "Enter name of workshop\r\nKey sequence 'Atelier1' with focus on 'None.TEdit'.", repo.None.TEditInfo, new RecordItemIndex(19));
            repo.None.TEdit.EnsureVisible();
            Keyboard.Press("Atelier1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'None.ButtonOK' at 32;13.", repo.None.ButtonOKInfo, new RecordItemIndex(20));
            repo.None.ButtonOK.Click("32;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext'.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(21));
            Validate.Exists(repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext' at 0;0.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(22));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext.Click("0;0");
            Delay.Milliseconds(0);
            
            // Choix profil
            Report.Log(ReportLevel.Info, "Mouse", "Choix profil\r\nMouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.ProgStatusBox' at 391;17.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.ProgStatusBoxInfo, new RecordItemIndex(23));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.ProgStatusBox.Click("391;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'None.FrenchMecaniqueGenerale' at 88;6.", repo.None.FrenchMecaniqueGeneraleInfo, new RecordItemIndex(24));
            repo.None.FrenchMecaniqueGenerale.Click("88;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext'.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(25));
            Validate.Exists(repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext' at 47;13.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(26));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext.Click("47;13");
            Delay.Milliseconds(0);
            
            // Choix mode DNC PROD
            Report.Log(ReportLevel.Info, "Mouse", "Choix mode DNC PROD\r\nMouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.CbProfil' at 389;13.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.CbProfilInfo, new RecordItemIndex(27));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.CbProfil.Click("389;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'None.DNCPlusSuiviDeProduction' at Center.", repo.None.DNCPlusSuiviDeProductionInfo, new RecordItemIndex(28));
            repo.None.DNCPlusSuiviDeProduction.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext'.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(29));
            Validate.Exists(repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext' at 44;13.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(30));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext.Click("44;13");
            Delay.Milliseconds(0);
            
            // Choix type de démargae
            Report.Log(ReportLevel.Info, "Mouse", "Choix type de démargae\r\nMouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.DemarrerAvecPageLogin' at 7;8.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.DemarrerAvecPageLoginInfo, new RecordItemIndex(31));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.DemarrerAvecPageLogin.Click("7;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext'.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(32));
            Validate.Exists(repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext' at 49;12.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNextInfo, new RecordItemIndex(33));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BNext.Click("49;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BClose'.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BCloseInfo, new RecordItemIndex(34));
            Validate.Exists(repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BCloseInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BClose' at Center.", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BCloseInfo, new RecordItemIndex(35));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.Panel3.BClose.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'CworkAssitantConfig.AssistantDeConfigurationDeCWork'", repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.SelfInfo, new ActionTimeout(30000), new RecordItemIndex(36));
            repo.CworkAssitantConfig.AssistantDeConfigurationDeCWork.SelfInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(37));
            Delay.Duration(10000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
