///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CworkTestLib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StopStartComPcService recording.
    /// </summary>
    [TestModule("24267d96-bb91-4a7f-9951-03996afe4d19", ModuleType.Recording, 1)]
    public partial class StopStartComPcService : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CworkTestLibRepository repository.
        /// </summary>
        public static CworkTestLibRepository repo = CworkTestLibRepository.Instance;

        static StopStartComPcService instance = new StopStartComPcService();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StopStartComPcService()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StopStartComPcService Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.CWork202195.MenuItemOutils' at 26;8.", repo.CworkMainForm.CWork202195.MenuItemOutilsInfo, new RecordItemIndex(0));
            //repo.CworkMainForm.CWork202195.MenuItemOutils.Click("26;8");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cwork2024983DEV.MenuItemOutils' at Center.", repo.Cwork2024983DEV.MenuItemOutilsInfo, new RecordItemIndex(1));
            repo.Cwork2024983DEV.MenuItemOutils.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.Cwork.MenuItemGererMoteur' at 61;15.", repo.CworkMainForm.Cwork.MenuItemGererMoteurInfo, new RecordItemIndex(2));
            repo.CworkMainForm.Cwork.MenuItemGererMoteur.Click("61;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GestionDesServeursEtMoteurs.ActionsSurMoteurs' at 42;4.", repo.GestionDesServeursEtMoteurs.ActionsSurMoteursInfo, new RecordItemIndex(3));
            repo.GestionDesServeursEtMoteurs.ActionsSurMoteurs.Click("42;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GestionDesServeursEtMoteurs.BStopComPC' at 22;18.", repo.GestionDesServeursEtMoteurs.BStopComPCInfo, new RecordItemIndex(4));
            repo.GestionDesServeursEtMoteurs.BStopComPC.Click("22;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'GestionDesServeursEtMoteurs.BStartComPC'.", repo.GestionDesServeursEtMoteurs.BStartComPCInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.GestionDesServeursEtMoteurs.BStartComPCInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GestionDesServeursEtMoteurs.BStartComPC' at 19;14.", repo.GestionDesServeursEtMoteurs.BStartComPCInfo, new RecordItemIndex(6));
            repo.GestionDesServeursEtMoteurs.BStartComPC.Click("19;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'GestionDesServeursEtMoteurs.BStopComPC'", repo.GestionDesServeursEtMoteurs.BStopComPCInfo, new RecordItemIndex(7));
            repo.GestionDesServeursEtMoteurs.BStopComPCInfo.WaitForAttributeEqual(60000, "Enabled", "True");
            
            // On attend de voir si le moteur tient
            Report.Log(ReportLevel.Info, "Delay", "On attend de voir si le moteur tient\r\nWaiting for 10s.", new RecordItemIndex(8));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'GestionDesServeursEtMoteurs.BStopComPC'", repo.GestionDesServeursEtMoteurs.BStopComPCInfo, new RecordItemIndex(9));
            repo.GestionDesServeursEtMoteurs.BStopComPCInfo.WaitForAttributeEqual(60000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GestionDesServeursEtMoteurs.Valider' at 48;12.", repo.GestionDesServeursEtMoteurs.ValiderInfo, new RecordItemIndex(10));
            repo.GestionDesServeursEtMoteurs.Valider.Click("48;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
