///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_7
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClickFindByContent recording.
    /// </summary>
    [TestModule("c2d07328-b7ed-41bd-8f0b-15e9f2032abf", ModuleType.Recording, 1)]
    public partial class ClickFindByContent : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_7Repository repository.
        /// </summary>
        public static Sprint_9_7Repository repo = Sprint_9_7Repository.Instance;

        static ClickFindByContent instance = new ClickFindByContent();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClickFindByContent()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClickFindByContent Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2022963DEV.StationsTiles' at 165;92.", repo.CWork2022963DEV.StationsTilesInfo, new RecordItemIndex(0));
            repo.CWork2022963DEV.StationsTiles.Click("165;92");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2022963DEV.BShowProgram' at 59;27.", repo.CWork2022963DEV.BShowProgramInfo, new RecordItemIndex(1));
            repo.CWork2022963DEV.BShowProgram.Click("59;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'CWork2022963DEV.BtContentSearchEngine' at 125;13.", repo.CWork2022963DEV.BtContentSearchEngineInfo, new RecordItemIndex(2));
            repo.CWork2022963DEV.BtContentSearchEngine.DoubleClick("125;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2022963DEV.ColorMemo' at 264;26.", repo.CWork2022963DEV.ColorMemoInfo, new RecordItemIndex(3));
            repo.CWork2022963DEV.ColorMemo.Click("264;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 47}testCwork' with focus on 'CWork2022963DEV'.", repo.CWork2022963DEV.SelfInfo, new RecordItemIndex(4));
            repo.CWork2022963DEV.Self.EnsureVisible();
            Keyboard.Press("{Back 47}testCwork");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2022963DEV.BtnFind' at 19;57.", repo.CWork2022963DEV.BtnFindInfo, new RecordItemIndex(5));
            repo.CWork2022963DEV.BtnFind.Click("19;57");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'CWork2022963DEV.Png12' at 70;8.", repo.CWork2022963DEV.Png12Info, new RecordItemIndex(6));
            repo.CWork2022963DEV.Png12.DoubleClick("70;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'VersionsDeDocument' at 1158;10.", repo.VersionsDeDocument.SelfInfo, new RecordItemIndex(7));
            repo.VersionsDeDocument.Self.MoveTo("1158;10");
            repo.VersionsDeDocument.Self.MouseDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'VersionsDeDocument' at 1175;12.", repo.VersionsDeDocument.SelfInfo, new RecordItemIndex(8));
            repo.VersionsDeDocument.Self.MoveTo("1175;12");
            repo.VersionsDeDocument.Self.MouseUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
