///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint9_5_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckPartnerInAbout recording.
    /// </summary>
    [TestModule("d8f18f58-a71b-4bcd-943b-01737c4186e1", ModuleType.Recording, 1)]
    public partial class CheckPartnerInAbout : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestFix9_5_2Repository repository.
        /// </summary>
        public static TestFix9_5_2Repository repo = TestFix9_5_2Repository.Instance;

        static CheckPartnerInAbout instance = new CheckPartnerInAbout();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckPartnerInAbout()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckPartnerInAbout Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2021951.MenuItemAide' at 23;9.", repo.CWork2021951.MenuItemAideInfo, new RecordItemIndex(0));
            //repo.CWork2021951.MenuItemAide.Click("23;9");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cwork2024983DEV.MenuItemHelp' at Center.", repo.Cwork2024983DEV.MenuItemHelpInfo, new RecordItemIndex(1));
            repo.Cwork2024983DEV.MenuItemHelp.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cwork.MenuItem' at 62;16.", repo.Cwork.MenuItemInfo, new RecordItemIndex(2));
            repo.Cwork.MenuItem.Click("62;16");
            Delay.Milliseconds(0);
            
            // Si pas de code partenaire c'est smcom qui est affiché
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nSi pas de code partenaire c'est smcom qui est affiché\r\nValidating AttributeEqual (Text='Smcom software') on item 'FormApropos.SmcomSoftware'.", repo.FormApropos.SmcomSoftwareInfo, new RecordItemIndex(3));
                Validate.AttributeEqual(repo.FormApropos.SmcomSoftwareInfo, "Text", "Smcom software", null, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormApropos.BClose' at 49;12.", repo.FormApropos.BCloseInfo, new RecordItemIndex(4));
            repo.FormApropos.BClose.Click("49;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
