///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint9_5_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateAdditionalCprodStates recording.
    /// </summary>
    [TestModule("e3438838-2f90-4351-8394-91f2db01ef2a", ModuleType.Recording, 1)]
    public partial class CreateAdditionalCprodStates : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestFix9_5_2Repository repository.
        /// </summary>
        public static TestFix9_5_2Repository repo = TestFix9_5_2Repository.Instance;

        static CreateAdditionalCprodStates instance = new CreateAdditionalCprodStates();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateAdditionalCprodStates()
        {
            NbStates = "2";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateAdditionalCprodStates Instance
        {
            get { return instance; }
        }

#region Variables

        string _NbStates;

        /// <summary>
        /// Gets or sets the value of variable NbStates.
        /// </summary>
        [TestVariable("44de9738-e1c3-40a0-829b-6eda7542d255")]
        public string NbStates
        {
            get { return _NbStates; }
            set { _NbStates = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            AddCprodStates(ValueConverter.ArgumentFromString<int>("nbStates", NbStates));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
