///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint9_5_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifCompareWidth recording.
    /// </summary>
    [TestModule("b220e9c0-c48c-4547-90d7-0400a7fb7d4a", ModuleType.Recording, 1)]
    public partial class VerifCompareWidth : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestFix9_5_2Repository repository.
        /// </summary>
        public static TestFix9_5_2Repository repo = TestFix9_5_2Repository.Instance;

        static VerifCompareWidth instance = new VerifCompareWidth();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifCompareWidth()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifCompareWidth Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable CNC.
        /// </summary>
        [TestVariable("73999e4d-fd36-426f-99e8-93d40a4610d6")]
        public string CNC
        {
            get { return repo.CNC; }
            set { repo.CNC = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // selection CNC
            Report.Log(ReportLevel.Info, "Mouse", "selection CNC\r\nMouse Left DoubleClick item 'CworkMainForm1.Cnc' at 27;14.", repo.CworkMainForm1.CncInfo, new RecordItemIndex(0));
            repo.CworkMainForm1.Cnc.DoubleClick("27;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2021951.BSingleSelect' at Center.", repo.CWork2021951.BSingleSelectInfo, new RecordItemIndex(1));
            repo.CWork2021951.BSingleSelect.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(2));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.Png1' at 54;6.", repo.CworkMainForm1.Png1Info, new RecordItemIndex(3));
            repo.CworkMainForm1.Png1.Click("54;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.Png10' at 54;4.", repo.CworkMainForm1.Png10Info, new RecordItemIndex(4));
            repo.CworkMainForm1.Png10.Click("54;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.BCompare' at 46;23.", repo.CworkMainForm1.BCompareInfo, new RecordItemIndex(5));
            repo.CworkMainForm1.BCompare.Click("46;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='png1') on item 'VersionsDeDocument.Png1'.", repo.VersionsDeDocument.Png1Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.VersionsDeDocument.Png1Info, "Text", "png1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VersionsDeDocument.BOpenVersion' at 48;18.", repo.VersionsDeDocument.BOpenVersionInfo, new RecordItemIndex(7));
            repo.VersionsDeDocument.BOpenVersion.Click("48;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(8));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='png10') on item 'VersionsDeDocument.Png1'.", repo.VersionsDeDocument.Png1Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.VersionsDeDocument.Png1Info, "Text", "png10", null, new Validate.Options(){GracePeriod=30000});
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VersionsDeDocument.BOpenVersion' at 42;15.", repo.VersionsDeDocument.BOpenVersionInfo, new RecordItemIndex(10));
            repo.VersionsDeDocument.BOpenVersion.Click("42;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (RawText='Document: png1  Machine: Cnc-1  Status: VALIDÉ Indice: A/0  Dossier: ImportFAO\\') on item 'CworkMainForm1.DocumentPng1MachineCnc1Status'.", repo.CworkMainForm1.DocumentPng1MachineCnc1StatusInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.CworkMainForm1.DocumentPng1MachineCnc1StatusInfo, "RawText", "Document: png1  Machine: Cnc-1  Status: VALIDÉ Indice: A/0  Dossier: ImportFAO\\");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'CworkMainForm1.TCodeEdit'.", repo.CworkMainForm1.TCodeEditInfo, new RecordItemIndex(12));
            Validate.Exists(repo.CworkMainForm1.TCodeEditInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
