///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_7_4
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MultiselectProg recording.
    /// </summary>
    [TestModule("98b176af-9d90-419c-bc5c-695781cf4b00", ModuleType.Recording, 1)]
    public partial class MultiselectProg : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_7_4Repository repository.
        /// </summary>
        public static Sprint_9_7_4Repository repo = Sprint_9_7_4Repository.Instance;

        static MultiselectProg instance = new MultiselectProg();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MultiselectProg()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MultiselectProg Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2023973DEV.Cnc1' at 32;17.", repo.CWork2023973DEV.Cnc1Info, new RecordItemIndex(0));
            repo.CWork2023973DEV.Cnc1.Click("32;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2023973DEV.BShowProgram' at 54;25.", repo.CWork2023973DEV.BShowProgramInfo, new RecordItemIndex(1));
            repo.CWork2023973DEV.BShowProgram.Click("54;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2023973DEV.BSingleSelect' at 76;11.", repo.CWork2023973DEV.BSingleSelectInfo, new RecordItemIndex(2));
            repo.CWork2023973DEV.BSingleSelect.Click("76;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2023973DEV.PartsView.Png1' at 54;10.", repo.CWork2023973DEV.PartsView.Png1Info, new RecordItemIndex(3));
            repo.CWork2023973DEV.PartsView.Png1.Click("54;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2023973DEV.PartsView.Png2' at 55;10.", repo.CWork2023973DEV.PartsView.Png2Info, new RecordItemIndex(4));
            repo.CWork2023973DEV.PartsView.Png2.Click("55;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2023973DEV.PartsView1' at 186;188.", repo.CWork2023973DEV.PartsView1Info, new RecordItemIndex(5));
            repo.CWork2023973DEV.PartsView1.Click("186;188");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
