///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_7_4
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NavigateFolderAbotherCnc recording.
    /// </summary>
    [TestModule("7298d18a-770a-4ee9-8d79-a8161283307a", ModuleType.Recording, 1)]
    public partial class NavigateFolderAbotherCnc : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_7_4Repository repository.
        /// </summary>
        public static Sprint_9_7_4Repository repo = Sprint_9_7_4Repository.Instance;

        static NavigateFolderAbotherCnc instance = new NavigateFolderAbotherCnc();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NavigateFolderAbotherCnc()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NavigateFolderAbotherCnc Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'CWork2023973DEV.ImportFAO1' at 34;8.", repo.CWork2023973DEV.ImportFAO1Info, new RecordItemIndex(0));
            repo.CWork2023973DEV.ImportFAO1.DoubleClick("34;8");
            Delay.Milliseconds(0);
            
            // Validate warning popup windows exist
            Report.Log(ReportLevel.Info, "Validation", "Validate warning popup windows exist\r\nValidating Exists on item 'Confirmer'.", repo.Confirmer.SelfInfo, new RecordItemIndex(1));
            Validate.Exists(repo.Confirmer.SelfInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Confirmer.ButtonOui' at 46;10.", repo.Confirmer.ButtonOuiInfo, new RecordItemIndex(2));
            repo.Confirmer.ButtonOui.Click("46;10");
            Delay.Milliseconds(0);
            
            // Validate Navigation okay
            Report.Log(ReportLevel.Info, "Validation", "Validate Navigation okay\r\nValidating AttributeEqual (RawText='Cnc-2\\ImportFAO\\') on item 'CWork2023973DEV.StaticText'.", repo.CWork2023973DEV.StaticTextInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.CWork2023973DEV.StaticTextInfo, "RawText", "Cnc-2\\ImportFAO\\");
            Delay.Milliseconds(100);
            
            // Valide buton "recevoir" exists
            Report.Log(ReportLevel.Info, "Validation", "Valide buton \"recevoir\" exists\r\nValidating Exists on item 'CWork2023973DEV.BCommReceive'.", repo.CWork2023973DEV.BCommReceiveInfo, new RecordItemIndex(4));
            Validate.Exists(repo.CWork2023973DEV.BCommReceiveInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
