///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_7_4
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NavigateFolderSameCNC recording.
    /// </summary>
    [TestModule("60681a74-bed5-41fe-9c5c-e549896d0b59", ModuleType.Recording, 1)]
    public partial class NavigateFolderSameCNC : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_7_4Repository repository.
        /// </summary>
        public static Sprint_9_7_4Repository repo = Sprint_9_7_4Repository.Instance;

        static NavigateFolderSameCNC instance = new NavigateFolderSameCNC();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NavigateFolderSameCNC()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NavigateFolderSameCNC Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'CWork2023973DEV.ImportFAO' at 23;8.", repo.CWork2023973DEV.ImportFAOInfo, new RecordItemIndex(0));
            repo.CWork2023973DEV.ImportFAO.DoubleClick("23;8");
            Delay.Milliseconds(0);
            
            // Verify we are in Right folder
            Report.Log(ReportLevel.Info, "Validation", "Verify we are in Right folder\r\nValidating AttributeEqual (RawText='Cnc-1\\ImportFAO\\') on item 'CWork2023973DEV.StaticText'.", repo.CWork2023973DEV.StaticTextInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.CWork2023973DEV.StaticTextInfo, "RawText", "Cnc-1\\ImportFAO\\");
            Delay.Milliseconds(100);
            
            // Verify we are still connected
            Report.Log(ReportLevel.Info, "Validation", "Verify we are still connected\r\nValidating AttributeEqual (Text='Nom') on item 'CWork2023973DEV.ColumnNom'.", repo.CWork2023973DEV.ColumnNomInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.CWork2023973DEV.ColumnNomInfo, "Text", "Nom");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
