///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_7_4
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateCheckedPrg recording.
    /// </summary>
    [TestModule("4c241483-978d-4ad4-adbb-884f9584297b", ModuleType.Recording, 1)]
    public partial class ValidateCheckedPrg : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_7_4Repository repository.
        /// </summary>
        public static Sprint_9_7_4Repository repo = Sprint_9_7_4Repository.Instance;

        static ValidateCheckedPrg instance = new ValidateCheckedPrg();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateCheckedPrg()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateCheckedPrg Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=4,Y=1,Width=67,Height=15}) on item 'CWork2023973DEV.PartsView.Png1'.", repo.CWork2023973DEV.PartsView.Png1Info, new RecordItemIndex(0));
            Validate.ContainsImage(repo.CWork2023973DEV.PartsView.Png1Info, Png1_Screenshot1, Png1_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=6,Y=3,Width=69,Height=13}) on item 'CWork2023973DEV.PartsView.Png2'.", repo.CWork2023973DEV.PartsView.Png2Info, new RecordItemIndex(1));
            Validate.ContainsImage(repo.CWork2023973DEV.PartsView.Png2Info, Png2_Screenshot1, Png2_Screenshot1_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Png1_Screenshot1
        { get { return repo.CWork2023973DEV.PartsView.Png1Info.GetScreenshot1(new Rectangle(4, 1, 67, 15)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Png1_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Png2_Screenshot1
        { get { return repo.CWork2023973DEV.PartsView.Png2Info.GetScreenshot1(new Rectangle(6, 3, 69, 13)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Png2_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
