///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_6_3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PopulatePgrInCworkWithCnet recording.
    /// </summary>
    [TestModule("63046580-557b-419a-a2f7-e5986a6469a5", ModuleType.Recording, 1)]
    public partial class PopulatePgrInCworkWithCnet : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_6_3Repository repository.
        /// </summary>
        public static Sprint_9_6_3Repository repo = Sprint_9_6_3Repository.Instance;

        static PopulatePgrInCworkWithCnet instance = new PopulatePgrInCworkWithCnet();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PopulatePgrInCworkWithCnet()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PopulatePgrInCworkWithCnet Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CNetDNC.Decharger' at 94;20.", repo.CNetDNC.DechargerInfo, new RecordItemIndex(0));
            repo.CNetDNC.Decharger.Click("94;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CNetDNC.ToutSauver' at 92;22.", repo.CNetDNC.ToutSauverInfo, new RecordItemIndex(1));
            repo.CNetDNC.ToutSauver.Click("92;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(2));
            Delay.Duration(10000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
