///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_6_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckstatesTimeOnMatrice recording.
    /// </summary>
    [TestModule("69243765-4be0-4797-93c0-b0fa94c33469", ModuleType.Recording, 1)]
    public partial class CheckstatesTimeOnMatrice : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_6_2Repository repository.
        /// </summary>
        public static Sprint_9_6_2Repository repo = Sprint_9_6_2Repository.Instance;

        static CheckstatesTimeOnMatrice instance = new CheckstatesTimeOnMatrice();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckstatesTimeOnMatrice()
        {
            TotalDayTimeMax = "24:00:00";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckstatesTimeOnMatrice Instance
        {
            get { return instance; }
        }

#region Variables

        string _TotalDayTimeMax;

        /// <summary>
        /// Gets or sets the value of variable TotalDayTimeMax.
        /// </summary>
        [TestVariable("fb693b2e-e82c-4da7-88ca-b5a866b8db1b")]
        public string TotalDayTimeMax
        {
            get { return _TotalDayTimeMax; }
            set { _TotalDayTimeMax = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2022962DEV.StationsTiles' at 173;75.", repo.CWork2022962DEV.StationsTilesInfo, new RecordItemIndex(0));
            repo.CWork2022962DEV.StationsTiles.Click("173;75");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2022962DEV.StationsTiles' at 161;-33.", repo.CWork2022962DEV.StationsTilesInfo, new RecordItemIndex(1));
            repo.CWork2022962DEV.StationsTiles.Click("161;-33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.HistoriqueDeProduction.ToolPanelTab' at 11;29.", repo.CworkMainForm1.HistoriqueDeProduction.ToolPanelTabInfo, new RecordItemIndex(2));
            repo.CworkMainForm1.HistoriqueDeProduction.ToolPanelTab.Click("11;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.HistoriqueDeProduction.BtnMonth' at 20;43.", repo.CworkMainForm1.HistoriqueDeProduction.BtnMonthInfo, new RecordItemIndex(3));
            repo.CworkMainForm1.HistoriqueDeProduction.BtnMonth.Click("20;43");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.HistoriqueDeProduction.BtnMonth' at -109;-213.", repo.CworkMainForm1.HistoriqueDeProduction.BtnMonthInfo, new RecordItemIndex(4));
            repo.CworkMainForm1.HistoriqueDeProduction.BtnMonth.Click("-109;-213");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.Systeme' at 179;471.", repo.CworkMainForm1.SystemeInfo, new RecordItemIndex(5));
            repo.CworkMainForm1.Systeme.Click("179;471");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.HistoriqueDeProduction.ToolPanelTab' at 11;41.", repo.CworkMainForm1.HistoriqueDeProduction.ToolPanelTabInfo, new RecordItemIndex(6));
            repo.CworkMainForm1.HistoriqueDeProduction.ToolPanelTab.Click("11;41");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.HistoriqueDeProduction.ToolPanelTab' at 131;142.", repo.CworkMainForm1.HistoriqueDeProduction.ToolPanelTabInfo, new RecordItemIndex(7));
            repo.CworkMainForm1.HistoriqueDeProduction.ToolPanelTab.Click("131;142");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.HistoriqueDeProduction.ChoixDate' at 133;119.", repo.CworkMainForm1.HistoriqueDeProduction.ChoixDateInfo, new RecordItemIndex(8));
            repo.CworkMainForm1.HistoriqueDeProduction.ChoixDate.Click("133;119");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>$TotalDayTimeMax) on item 'CworkMainForm2.CWork202195.Cell240000'.", repo.CworkMainForm2.CWork202195.Cell240000Info, new RecordItemIndex(9));
            Validate.AttributeContains(repo.CworkMainForm2.CWork202195.Cell240000Info, "Text", TotalDayTimeMax);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
