///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_6_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConfigureNetworkImport recording.
    /// </summary>
    [TestModule("8de96da1-a317-4f82-b862-7bf08d7f4db6", ModuleType.Recording, 1)]
    public partial class ConfigureNetworkImport : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_6_2Repository repository.
        /// </summary>
        public static Sprint_9_6_2Repository repo = Sprint_9_6_2Repository.Instance;

        static ConfigureNetworkImport instance = new ConfigureNetworkImport();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConfigureNetworkImport()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConfigureNetworkImport Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'CWork2022962DEV.StationsTiles' at 167;104.", repo.CWork2022962DEV.StationsTilesInfo, new RecordItemIndex(0));
            repo.CWork2022962DEV.StationsTiles.Click(System.Windows.Forms.MouseButtons.Right, "167;104");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2022962DEV.StationsTiles' at 227;309.", repo.CWork2022962DEV.StationsTilesInfo, new RecordItemIndex(1));
            repo.CWork2022962DEV.StationsTiles.Click("227;309");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ChoixDuneConfiguration.FanucEthernet' at 22;8.", repo.ChoixDuneConfiguration.FanucEthernetInfo, new RecordItemIndex(2));
            repo.ChoixDuneConfiguration.FanucEthernet.Click("22;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ChoixDuneConfiguration.ElementBOk' at 65;22.", repo.ChoixDuneConfiguration.ElementBOkInfo, new RecordItemIndex(3));
            repo.ChoixDuneConfiguration.ElementBOk.Click("65;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.CaptureReseau' at 44;8.", repo.ProprietesPourCnc1.CaptureReseauInfo, new RecordItemIndex(4));
            repo.ProprietesPourCnc1.CaptureReseau.Click("44;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.BAddNetworkScan' at 16;10.", repo.ProprietesPourCnc1.BAddNetworkScanInfo, new RecordItemIndex(5));
            repo.ProprietesPourCnc1.BAddNetworkScan.Click("16;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c' with focus on 'ChangerLeDossierDimportationAutomati'.", repo.ChangerLeDossierDimportationAutomati.SelfInfo, new RecordItemIndex(6));
            repo.ChangerLeDossierDimportationAutomati.Self.EnsureVisible();
            Keyboard.Press("c");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ChangerLeDossierDimportationAutomati.EdNetworkDir' at 63;4.", repo.ChangerLeDossierDimportationAutomati.EdNetworkDirInfo, new RecordItemIndex(7));
            repo.ChangerLeDossierDimportationAutomati.EdNetworkDir.MoveTo("63;4");
            repo.ChangerLeDossierDimportationAutomati.EdNetworkDir.MouseDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ChangerLeDossierDimportationAutomati.EdNetworkDir' at 47;7.", repo.ChangerLeDossierDimportationAutomati.EdNetworkDirInfo, new RecordItemIndex(8));
            repo.ChangerLeDossierDimportationAutomati.EdNetworkDir.MoveTo("47;7");
            repo.ChangerLeDossierDimportationAutomati.EdNetworkDir.MouseUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ':{LControlKey down}{RMenu down}{D8}{RMenu up}{LControlKey up}{LControlKey up}Cwork' with focus on 'ChangerLeDossierDimportationAutomati'.", repo.ChangerLeDossierDimportationAutomati.SelfInfo, new RecordItemIndex(9));
            repo.ChangerLeDossierDimportationAutomati.Self.EnsureVisible();
            Keyboard.Press(":{LControlKey down}{RMenu down}{D8}{RMenu up}{LControlKey up}{LControlKey up}Cwork");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test' with focus on 'ChangerLeDossierDimportationAutomati'.", repo.ChangerLeDossierDimportationAutomati.SelfInfo, new RecordItemIndex(10));
            repo.ChangerLeDossierDimportationAutomati.Self.EnsureVisible();
            Keyboard.Press("Test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Auto' with focus on 'ChangerLeDossierDimportationAutomati'.", repo.ChangerLeDossierDimportationAutomati.SelfInfo, new RecordItemIndex(11));
            repo.ChangerLeDossierDimportationAutomati.Self.EnsureVisible();
            Keyboard.Press("Auto");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{RMenu down}{D8}{LControlKey up}{LControlKey up}{RMenu up}Import' with focus on 'ChangerLeDossierDimportationAutomati'.", repo.ChangerLeDossierDimportationAutomati.SelfInfo, new RecordItemIndex(12));
            repo.ChangerLeDossierDimportationAutomati.Self.EnsureVisible();
            Keyboard.Press("{LControlKey down}{RMenu down}{D8}{LControlKey up}{LControlKey up}{RMenu up}Import");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'FAO' with focus on 'ChangerLeDossierDimportationAutomati'.", repo.ChangerLeDossierDimportationAutomati.SelfInfo, new RecordItemIndex(13));
            repo.ChangerLeDossierDimportationAutomati.Self.EnsureVisible();
            Keyboard.Press("FAO");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ChangerLeDossierDimportationAutomati.Valider' at 41;9.", repo.ChangerLeDossierDimportationAutomati.ValiderInfo, new RecordItemIndex(14));
            repo.ChangerLeDossierDimportationAutomati.Valider.Click("41;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.ButtonAppliquer' at 42;11.", repo.ProprietesPourCnc1.ButtonAppliquerInfo, new RecordItemIndex(15));
            repo.ProprietesPourCnc1.ButtonAppliquer.Click("42;11");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
