///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_7_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AutorizeAdministratorToResetPart recording.
    /// </summary>
    [TestModule("9974d5dc-f810-426c-acc4-0e88e30d5854", ModuleType.Recording, 1)]
    public partial class AutorizeAdministratorToResetPart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_7_2Repository repository.
        /// </summary>
        public static Sprint_9_7_2Repository repo = Sprint_9_7_2Repository.Instance;

        static AutorizeAdministratorToResetPart instance = new AutorizeAdministratorToResetPart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AutorizeAdministratorToResetPart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AutorizeAdministratorToResetPart Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork2023972DEV.MenuItemOutils' at 26;9.", repo.CWork2023972DEV.MenuItemOutilsInfo, new RecordItemIndex(0));
            //repo.CWork2023972DEV.MenuItemOutils.Click("26;9");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cwork2024983DEV.MenuItemOutils' at Center.", repo.Cwork2024983DEV.MenuItemOutilsInfo, new RecordItemIndex(1));
            repo.Cwork2024983DEV.MenuItemOutils.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cwork.MenuItem1' at 65;9.", repo.Cwork.MenuItem1Info, new RecordItemIndex(2));
            repo.Cwork.MenuItem1.Click("65;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Preferences.DroitsDesUtilisateurs' at 63;7.", repo.Preferences.DroitsDesUtilisateursInfo, new RecordItemIndex(3));
            repo.Preferences.DroitsDesUtilisateurs.Click("63;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Preferences.Administrateurs' at 55;5.", repo.Preferences.AdministrateursInfo, new RecordItemIndex(4));
            repo.Preferences.Administrateurs.DoubleClick("55;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -1920 units.", new RecordItemIndex(5));
            Mouse.ScrollWheel(-1920);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AjoutDunGroupe.ListItemPeutInitialiserLeNombreDe' at 77;4.", repo.AjoutDunGroupe.ListItemPeutInitialiserLeNombreDeInfo, new RecordItemIndex(6));
            repo.AjoutDunGroupe.ListItemPeutInitialiserLeNombreDe.Click("77;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AjoutDunGroupe.ListItemPeutInitialiserLeNombreDe' at 11;6.", repo.AjoutDunGroupe.ListItemPeutInitialiserLeNombreDeInfo, new RecordItemIndex(7));
            repo.AjoutDunGroupe.ListItemPeutInitialiserLeNombreDe.Click("11;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'AjoutDunGroupe.ButtonOK' at 43;11.", repo.AjoutDunGroupe.ButtonOKInfo, new RecordItemIndex(8));
            repo.AjoutDunGroupe.ButtonOK.MoveTo("43;11");
            repo.AjoutDunGroupe.ButtonOK.MouseDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'AjoutDunGroupe.ButtonOK' at 43;11.", repo.AjoutDunGroupe.ButtonOKInfo, new RecordItemIndex(9));
            repo.AjoutDunGroupe.ButtonOK.MoveTo("43;11");
            repo.AjoutDunGroupe.ButtonOK.MouseUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Preferences.ButtonOk' at 57;16.", repo.Preferences.ButtonOkInfo, new RecordItemIndex(10));
            repo.Preferences.ButtonOk.MoveTo("57;16");
            repo.Preferences.ButtonOk.MouseDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Preferences.ButtonOk' at 57;16.", repo.Preferences.ButtonOkInfo, new RecordItemIndex(11));
            repo.Preferences.ButtonOk.MoveTo("57;16");
            repo.Preferences.ButtonOk.MouseUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
