///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint9_6_1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConfigSendSMSsStateChange recording.
    /// </summary>
    [TestModule("b9f90801-7275-4baa-a4f6-48a9aa2f00a9", ModuleType.Recording, 1)]
    public partial class ConfigSendSMSsStateChange : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint9_6_1Repository repository.
        /// </summary>
        public static Sprint9_6_1Repository repo = Sprint9_6_1Repository.Instance;

        static ConfigSendSMSsStateChange instance = new ConfigSendSMSsStateChange();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConfigSendSMSsStateChange()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConfigSendSMSsStateChange Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork202296DEV.MenuItemOutils' at 20;7.", repo.CWork202296DEV.MenuItemOutilsInfo, new RecordItemIndex(0));
            //repo.CWork202296DEV.MenuItemOutils.Click("20;7");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Cwork2024983DEV.MenuItemOutils' at Center.", repo.Cwork2024983DEV.MenuItemOutilsInfo, new RecordItemIndex(1));
            repo.Cwork2024983DEV.MenuItemOutils.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.Cwork.MenuItem3' at 63;11.", repo.CworkMainForm.Cwork.MenuItem3Info, new RecordItemIndex(2));
            repo.CworkMainForm.Cwork.MenuItem3.Click("63;11");
            Delay.Milliseconds(12370);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Preferences.GestionDesNotifications' at 57;6.", repo.Preferences.GestionDesNotificationsInfo, new RecordItemIndex(3));
            repo.Preferences.GestionDesNotifications.Click("57;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Preferences.BAddNotif' at 30;10.", repo.Preferences.BAddNotifInfo, new RecordItemIndex(4));
            repo.Preferences.BAddNotif.Click("30;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.Cwork.ChangementDetat' at Center.", repo.CworkMainForm.Cwork.ChangementDetatInfo, new RecordItemIndex(5));
            repo.CworkMainForm.Cwork.ChangementDetat.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Preferences.SelectionnerTout' at 183;8.", repo.Preferences.SelectionnerToutInfo, new RecordItemIndex(6));
            repo.Preferences.SelectionnerTout.Click("183;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Preferences.SelectionnerTout1' at 184;7.", repo.Preferences.SelectionnerTout1Info, new RecordItemIndex(7));
            repo.Preferences.SelectionnerTout1.Click("184;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Preferences.SelectionnerTout2' at 192;8.", repo.Preferences.SelectionnerTout2Info, new RecordItemIndex(8));
            repo.Preferences.SelectionnerTout2.Click("192;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Preferences.CbListNotifState' at 178;17.", repo.Preferences.CbListNotifStateInfo, new RecordItemIndex(9));
            repo.Preferences.CbListNotifState.Click("178;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'None.RawTextSMS' at 9;6.", repo.None.RawTextSMSInfo, new RecordItemIndex(10));
            repo.None.RawTextSMS.Click("9;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Preferences.ButtonOk' at 49;15.", repo.Preferences.ButtonOkInfo, new RecordItemIndex(11));
            repo.Preferences.ButtonOk.Click("49;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
