/*************************************
* creation base de RanorexTestCworkDb
*************************************/
USE [master]
GO

IF DB_ID('RanorexTestCworkDb') IS NOT NULL
	DROP DATABASE [RanorexTestCworkDb]
GO


CREATE DATABASE [RanorexTestCworkDb]
/* CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RanorexTestCworkDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RanorexTestCworkDb.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RanorexTestCworkDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RanorexTestCworkDb_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT*/
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RanorexTestCworkDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RanorexTestCworkDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RanorexTestCworkDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RanorexTestCworkDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RanorexTestCworkDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RanorexTestCworkDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RanorexTestCworkDb] SET  MULTI_USER 
GO

ALTER DATABASE [RanorexTestCworkDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RanorexTestCworkDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RanorexTestCworkDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RanorexTestCworkDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RanorexTestCworkDb] SET DELAYED_DURABILITY = DISABLED 
GO

/*ALTER DATABASE [RanorexTestCworkDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO*/

ALTER DATABASE [RanorexTestCworkDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RanorexTestCworkDb] SET  READ_WRITE 
GO


/**********************
* creation login
***********************/
IF SUSER_ID('RanorexTestCwork') IS NOT NULL
	DROP LOGIN [RanorexTestCwork]
GO

CREATE LOGIN [RanorexTestCwork] WITH PASSWORD='RanorexTestCwork', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

ALTER LOGIN [RanorexTestCwork] ENABLE
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [RanorexTestCwork]
GO
