///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DevAutomatisation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConfigLsv2AlarmAndPrgEvents recording.
    /// </summary>
    [TestModule("6af666ee-5d9e-4052-a91d-1e4aa8366b5a", ModuleType.Recording, 1)]
    public partial class ConfigLsv2AlarmAndPrgEvents : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DevAutomatisationRepository repository.
        /// </summary>
        public static DevAutomatisationRepository repo = DevAutomatisationRepository.Instance;

        static ConfigLsv2AlarmAndPrgEvents instance = new ConfigLsv2AlarmAndPrgEvents();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConfigLsv2AlarmAndPrgEvents()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConfigLsv2AlarmAndPrgEvents Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork202296.Cnc1' at 32;14.", repo.CWork202296.Cnc1Info, new RecordItemIndex(0));
            repo.CWork202296.Cnc1.Click("32;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CWork202296.BProperty' at 51;29.", repo.CWork202296.BPropertyInfo, new RecordItemIndex(1));
            repo.CWork202296.BProperty.Click("51;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ChoixDuneConfiguration.HeidenhainLSV2' at 60;3.", repo.ChoixDuneConfiguration.HeidenhainLSV2Info, new RecordItemIndex(2));
            repo.ChoixDuneConfiguration.HeidenhainLSV2.Click("60;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ChoixDuneConfiguration.ElementBOk' at 40;18.", repo.ChoixDuneConfiguration.ElementBOkInfo, new RecordItemIndex(3));
            repo.ChoixDuneConfiguration.ElementBOk.Click("40;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(4));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.TvCategory.LSV2' at 15;7.", repo.ProprietesPourCnc1.TvCategory.LSV2Info, new RecordItemIndex(5));
            repo.ProprietesPourCnc1.TvCategory.LSV2.Click("15;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.TabSheet11.TxtProdLSV2ip' at 4;9.", repo.ProprietesPourCnc1.TabSheet11.TxtProdLSV2ipInfo, new RecordItemIndex(6));
            repo.ProprietesPourCnc1.TabSheet11.TxtProdLSV2ip.Click("4;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad2}{NumPad7}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad1}' with focus on 'ProprietesPourCnc1.TabSheet11.TxtProdLSV2ip'.", repo.ProprietesPourCnc1.TabSheet11.TxtProdLSV2ipInfo, new RecordItemIndex(7));
            repo.ProprietesPourCnc1.TabSheet11.TxtProdLSV2ip.PressKeys("{NumPad1}{NumPad2}{NumPad7}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad0}{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.TvCategory.CollecteDevenements' at 32;7.", repo.ProprietesPourCnc1.TvCategory.CollecteDevenementsInfo, new RecordItemIndex(8));
            repo.ProprietesPourCnc1.TvCategory.CollecteDevenements.Click("32;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.TabSheet11.ActiverLaCollecteDesProgrammesEnCo' at 7;8.", repo.ProprietesPourCnc1.TabSheet11.ActiverLaCollecteDesProgrammesEnCoInfo, new RecordItemIndex(9));
            repo.ProprietesPourCnc1.TabSheet11.ActiverLaCollecteDesProgrammesEnCo.Click("7;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.TabSheet11.SomeButton' at 9;6.", repo.ProprietesPourCnc1.TabSheet11.SomeButtonInfo, new RecordItemIndex(10));
            repo.ProprietesPourCnc1.TabSheet11.SomeButton.Click("9;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ViaLSV2' at 32;3.", repo.List1000.ViaLSV2Info, new RecordItemIndex(11));
            repo.List1000.ViaLSV2.Click("32;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.TabSheet11.ActiverLaCollecteDesAlarmes' at 9;6.", repo.ProprietesPourCnc1.TabSheet11.ActiverLaCollecteDesAlarmesInfo, new RecordItemIndex(12));
            repo.ProprietesPourCnc1.TabSheet11.ActiverLaCollecteDesAlarmes.Click("9;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.SomeButton1' at 6;5.", repo.ProprietesPourCnc1.SomeButton1Info, new RecordItemIndex(13));
            repo.ProprietesPourCnc1.SomeButton1.Click("6;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.SomeButton1' at -99;38.", repo.ProprietesPourCnc1.SomeButton1Info, new RecordItemIndex(14));
            repo.ProprietesPourCnc1.SomeButton1.Click("-99;38");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.ButtonAppliquer' at 56;9.", repo.ProprietesPourCnc1.ButtonAppliquerInfo, new RecordItemIndex(15));
            repo.ProprietesPourCnc1.ButtonAppliquer.Click("56;9");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
