///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_7_1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CompareExportFilesCheckSumMazacam recording.
    /// </summary>
    [TestModule("ac06b093-f049-4062-8cd7-71c6d3a0a72d", ModuleType.Recording, 1)]
    public partial class CompareExportFilesCheckSumMazacam : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_7_1Repository repository.
        /// </summary>
        public static Sprint_9_7_1Repository repo = Sprint_9_7_1Repository.Instance;

        static CompareExportFilesCheckSumMazacam instance = new CompareExportFilesCheckSumMazacam();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CompareExportFilesCheckSumMazacam()
        {
            BIN = "Prog2.BIN";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CompareExportFilesCheckSumMazacam Instance
        {
            get { return instance; }
        }

#region Variables

        string _BIN;

        /// <summary>
        /// Gets or sets the value of variable BIN.
        /// </summary>
        [TestVariable("1d0e6746-87fd-4cce-a249-23fc8cb2d6d0")]
        public string BIN
        {
            get { return _BIN; }
            set { _BIN = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            CworkTestLib.UserCodeCollection.RunProgramAndWait("TestPrep\\ChecksumComp.bat", "Prog2.BIN", ValueConverter.ArgumentFromString<int>("waitSeconds", "10"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
