///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_7_1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteImportFaoAndCopyBin recording.
    /// </summary>
    [TestModule("47dc4514-d358-414e-81ef-4ba8b32578b8", ModuleType.Recording, 1)]
    public partial class DeleteImportFaoAndCopyBin : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_7_1Repository repository.
        /// </summary>
        public static Sprint_9_7_1Repository repo = Sprint_9_7_1Repository.Instance;

        static DeleteImportFaoAndCopyBin instance = new DeleteImportFaoAndCopyBin();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteImportFaoAndCopyBin()
        {
            NbFiles = "8";
            CopyBin = "TestPrep\\copyBin.BAT";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteImportFaoAndCopyBin Instance
        {
            get { return instance; }
        }

#region Variables

        string _NbFiles;

        /// <summary>
        /// Gets or sets the value of variable NbFiles.
        /// </summary>
        [TestVariable("10d35f86-a300-43ad-97e0-95f76c1afcad")]
        public string NbFiles
        {
            get { return _NbFiles; }
            set { _NbFiles = value; }
        }

        string _CopyBin;

        /// <summary>
        /// Gets or sets the value of variable CopyBin.
        /// </summary>
        [TestVariable("ee0be793-ac7b-4a0b-9315-32c3401c73ed")]
        public string CopyBin
        {
            get { return _CopyBin; }
            set { _CopyBin = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            CworkTestLib.UserCodeCollection.RunProgramAndWait(CopyBin, "", ValueConverter.ArgumentFromString<int>("waitSeconds", "1"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
