///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint9_6
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SendCallPng1SimpleWithTed recording.
    /// </summary>
    [TestModule("bdefa8fa-ba90-44e7-ad1b-f45fa1615146", ModuleType.Recording, 1)]
    public partial class SendCallPng1SimpleWithTed : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_6Repository repository.
        /// </summary>
        public static Sprint_9_6Repository repo = Sprint_9_6Repository.Instance;

        static SendCallPng1SimpleWithTed instance = new SendCallPng1SimpleWithTed();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SendCallPng1SimpleWithTed()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SendCallPng1SimpleWithTed Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTEDSCDemonstrationSoftwareV.LabelF2' at 35;14.", repo.FormTEDSCDemonstrationSoftwareV.LabelF2Info, new RecordItemIndex(0));
            repo.FormTEDSCDemonstrationSoftwareV.LabelF2.Click("35;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTEDSCDemonstrationSoftwareV.Memo1' at 25;8.", repo.FormTEDSCDemonstrationSoftwareV.Memo1Info, new RecordItemIndex(1));
            repo.FormTEDSCDemonstrationSoftwareV.Memo1.Click("25;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '%{Return}:5000{Return}(png1){Return}%{Return}' with focus on 'FormTEDSCDemonstrationSoftwareV.Memo1'.", repo.FormTEDSCDemonstrationSoftwareV.Memo1Info, new RecordItemIndex(2));
            repo.FormTEDSCDemonstrationSoftwareV.Memo1.PressKeys("%{Return}:5000{Return}(png1){Return}%{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTEDSCDemonstrationSoftwareV.BtEnvoi' at 29;12.", repo.FormTEDSCDemonstrationSoftwareV.BtEnvoiInfo, new RecordItemIndex(3));
            repo.FormTEDSCDemonstrationSoftwareV.BtEnvoi.Click("29;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTEDSCDemonstrationSoftwareV.LabelF2' at 28;11.", repo.FormTEDSCDemonstrationSoftwareV.LabelF2Info, new RecordItemIndex(4));
            repo.FormTEDSCDemonstrationSoftwareV.LabelF2.Click("28;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Text' to equal the specified value '%\r\nOpng1\r\n(png1)\r\nG10\r\n%\r\n'. Associated repository item: 'FormTEDSCDemonstrationSoftwareV.Memo1'", repo.FormTEDSCDemonstrationSoftwareV.Memo1Info, new RecordItemIndex(5));
            repo.FormTEDSCDemonstrationSoftwareV.Memo1Info.WaitForAttributeEqual(30000, "Text", "%\r\nOpng1\r\n(png1)\r\nG10\r\n%\r\n");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(6));
            Delay.Duration(30000, false);
            
            // ligne O1276(REF*P06U OP10) n'exite pas
            Report.Log(ReportLevel.Info, "Validation", "ligne O1276(REF*P06U OP10) n'exite pas\r\nValidating NotExists on item 'FormTEDSCDemonstrationSoftwareV.IĈČĐĎĂĪĜĞǺĨĆĎĮIĨĈĆA'.", repo.FormTEDSCDemonstrationSoftwareV.IĈČĐĎĂĪĜĞǺĨĆĎĮIĨĈĆAInfo, new RecordItemIndex(7));
            Validate.NotExists(repo.FormTEDSCDemonstrationSoftwareV.IĈČĐĎĂĪĜĞǺĨĆĎĮIĨĈĆAInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
