///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint9_6
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SendPng1Modified recording.
    /// </summary>
    [TestModule("2020b00b-1b64-4832-992c-02d53eeb2716", ModuleType.Recording, 1)]
    public partial class SendPng1Modified : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_6Repository repository.
        /// </summary>
        public static Sprint_9_6Repository repo = Sprint_9_6Repository.Instance;

        static SendPng1Modified instance = new SendPng1Modified();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SendPng1Modified()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SendPng1Modified Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTEDSCDemonstrationSoftwareV.LabelF2' at 35;14.", repo.FormTEDSCDemonstrationSoftwareV.LabelF2Info, new RecordItemIndex(0));
            repo.FormTEDSCDemonstrationSoftwareV.LabelF2.Click("35;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTEDSCDemonstrationSoftwareV.Memo1' at 25;8.", repo.FormTEDSCDemonstrationSoftwareV.Memo1Info, new RecordItemIndex(1));
            repo.FormTEDSCDemonstrationSoftwareV.Memo1.Click("25;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '%{Return}Opng1{Return}(png1){Return}G10{Return}%' with focus on 'FormTEDSCDemonstrationSoftwareV.Memo1'.", repo.FormTEDSCDemonstrationSoftwareV.Memo1Info, new RecordItemIndex(2));
            repo.FormTEDSCDemonstrationSoftwareV.Memo1.PressKeys("%{Return}Opng1{Return}(png1){Return}G10{Return}%");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTEDSCDemonstrationSoftwareV.BtEnvoi' at 29;12.", repo.FormTEDSCDemonstrationSoftwareV.BtEnvoiInfo, new RecordItemIndex(3));
            repo.FormTEDSCDemonstrationSoftwareV.BtEnvoi.Click("29;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(4));
            Delay.Duration(10000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
