///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint9_5_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Delete_HeidCom_Connection recording.
    /// </summary>
    [TestModule("580889b7-636b-48d2-a6b7-5d059ad9cb1e", ModuleType.Recording, 1)]
    public partial class Delete_HeidCom_Connection : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_5_3Repository repository.
        /// </summary>
        public static Sprint_9_5_3Repository repo = Sprint_9_5_3Repository.Instance;

        static Delete_HeidCom_Connection instance = new Delete_HeidCom_Connection();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Delete_HeidCom_Connection()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Delete_HeidCom_Connection Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm1.Cnc1' at Center.", repo.CworkMainForm1.Cnc1Info, new RecordItemIndex(0));
            repo.CworkMainForm1.Cnc1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CworkMainForm.CWork202195.BProperty' at Center.", repo.CworkMainForm.CWork202195.BPropertyInfo, new RecordItemIndex(1));
            repo.CworkMainForm.CWork202195.BProperty.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.HEIDCOM' at 35;9.", repo.ProprietesPourCnc1.HEIDCOMInfo, new RecordItemIndex(2));
            repo.ProprietesPourCnc1.HEIDCOM.Click("35;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.Configurer' at 64;15.", repo.ProprietesPourCnc1.ConfigurerInfo, new RecordItemIndex(3));
            repo.ProprietesPourCnc1.Configurer.Click("64;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HEIDENHAINDNCConnectionsRWPermiss.CellCW1' at 65;8.", repo.HEIDENHAINDNCConnectionsRWPermiss.CellCW1Info, new RecordItemIndex(4));
            repo.HEIDENHAINDNCConnectionsRWPermiss.CellCW1.Click("65;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HEIDENHAINDNCConnectionsRWPermiss.ButtonRemove' at 79;14.", repo.HEIDENHAINDNCConnectionsRWPermiss.ButtonRemoveInfo, new RecordItemIndex(5));
            repo.HEIDENHAINDNCConnectionsRWPermiss.ButtonRemove.Click("79;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DeleteConnectionWizard.ButtonOK' at 35;9.", repo.DeleteConnectionWizard.ButtonOKInfo, new RecordItemIndex(6));
            repo.DeleteConnectionWizard.ButtonOK.Click("35;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HEIDENHAINDNCConnectionsRWPermiss.Close' at 13;10.", repo.HEIDENHAINDNCConnectionsRWPermiss.CloseInfo, new RecordItemIndex(7));
            repo.HEIDENHAINDNCConnectionsRWPermiss.Close.Click("13;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProprietesPourCnc1.ButtonAppliquer' at 63;10.", repo.ProprietesPourCnc1.ButtonAppliquerInfo, new RecordItemIndex(8));
            repo.ProprietesPourCnc1.ButtonAppliquer.Click("63;10");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
