///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Sprint9_5_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Sprint_9_5_3Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("65bead2c-0c63-4c59-9c12-630ae995fddc")]
    public partial class Sprint_9_5_3Repository : RepoGenBaseFolder
    {
        static Sprint_9_5_3Repository instance = new Sprint_9_5_3Repository();
        Sprint_9_5_3RepositoryFolders.CworkMainForm1AppFolder _cworkmainform1;
        Sprint_9_5_3RepositoryFolders.CworkMainFormFolder _cworkmainform;
        Sprint_9_5_3RepositoryFolders.ProprietesPourCnc1AppFolder _proprietespourcnc1;
        Sprint_9_5_3RepositoryFolders.List1000AppFolder _list1000;
        Sprint_9_5_3RepositoryFolders.HEIDENHAINDNCConnectionsRWPermissAppFolder _heidenhaindncconnectionsrwpermiss;
        Sprint_9_5_3RepositoryFolders.WelcomeToTheAddConnectionWizardAppFolder _welcometotheaddconnectionwizard;
        Sprint_9_5_3RepositoryFolders.DeleteConnectionWizardAppFolder _deleteconnectionwizard;
        Sprint_9_5_3RepositoryFolders.NameAppFolder _name;
        Sprint_9_5_3RepositoryFolders.CNCTypeAppFolder _cnctype;
        Sprint_9_5_3RepositoryFolders.CWork2021953DEVAppFolder _cwork2021953dev;
        Sprint_9_5_3RepositoryFolders.AddConnectionWizardAppFolder _addconnectionwizard;
        Sprint_9_5_3RepositoryFolders.VersionsDeDocumentAppFolder _versionsdedocument;
        Sprint_9_5_3RepositoryFolders.EnregistrerSousAppFolder _enregistrersous;
        Sprint_9_5_3RepositoryFolders.CworkAppFolder _cwork;
        Sprint_9_5_3RepositoryFolders.TestPdfTravailMicrosoftEdgeAppFolder _testpdftravailmicrosoftedge;
        Sprint_9_5_3RepositoryFolders.Cwork2024983DEVAppFolder _cwork2024983dev;

        /// <summary>
        /// Gets the singleton class instance representing the Sprint_9_5_3Repository element repository.
        /// </summary>
        [RepositoryFolder("65bead2c-0c63-4c59-9c12-630ae995fddc")]
        public static Sprint_9_5_3Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Sprint_9_5_3Repository() 
            : base("Sprint_9_5_3Repository", "/", null, 0, false, "65bead2c-0c63-4c59-9c12-630ae995fddc", ".\\RepositoryImages\\Sprint_9_5_3Repository65bead2c.rximgres")
        {
            _cworkmainform1 = new Sprint_9_5_3RepositoryFolders.CworkMainForm1AppFolder(this);
            _cworkmainform = new Sprint_9_5_3RepositoryFolders.CworkMainFormFolder(this);
            _proprietespourcnc1 = new Sprint_9_5_3RepositoryFolders.ProprietesPourCnc1AppFolder(this);
            _list1000 = new Sprint_9_5_3RepositoryFolders.List1000AppFolder(this);
            _heidenhaindncconnectionsrwpermiss = new Sprint_9_5_3RepositoryFolders.HEIDENHAINDNCConnectionsRWPermissAppFolder(this);
            _welcometotheaddconnectionwizard = new Sprint_9_5_3RepositoryFolders.WelcomeToTheAddConnectionWizardAppFolder(this);
            _deleteconnectionwizard = new Sprint_9_5_3RepositoryFolders.DeleteConnectionWizardAppFolder(this);
            _name = new Sprint_9_5_3RepositoryFolders.NameAppFolder(this);
            _cnctype = new Sprint_9_5_3RepositoryFolders.CNCTypeAppFolder(this);
            _cwork2021953dev = new Sprint_9_5_3RepositoryFolders.CWork2021953DEVAppFolder(this);
            _addconnectionwizard = new Sprint_9_5_3RepositoryFolders.AddConnectionWizardAppFolder(this);
            _versionsdedocument = new Sprint_9_5_3RepositoryFolders.VersionsDeDocumentAppFolder(this);
            _enregistrersous = new Sprint_9_5_3RepositoryFolders.EnregistrerSousAppFolder(this);
            _cwork = new Sprint_9_5_3RepositoryFolders.CworkAppFolder(this);
            _testpdftravailmicrosoftedge = new Sprint_9_5_3RepositoryFolders.TestPdfTravailMicrosoftEdgeAppFolder(this);
            _cwork2024983dev = new Sprint_9_5_3RepositoryFolders.Cwork2024983DEVAppFolder(this);
        }

#region Variables

        string _day = "3";

        /// <summary>
        /// Gets or sets the value of variable day.
        /// </summary>
        [TestVariable("83b97544-5af4-4f01-8e6e-619ff2ed8969")]
        public string day
        {
            get { return _day; }
            set { _day = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("65bead2c-0c63-4c59-9c12-630ae995fddc")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The CworkMainForm1 folder.
        /// </summary>
        [RepositoryFolder("4ca955be-f314-4b5a-8c37-17773175b419")]
        public virtual Sprint_9_5_3RepositoryFolders.CworkMainForm1AppFolder CworkMainForm1
        {
            get { return _cworkmainform1; }
        }

        /// <summary>
        /// The CworkMainForm folder.
        /// </summary>
        [RepositoryFolder("4de63147-de44-4a47-b172-941b96d2e18f")]
        public virtual Sprint_9_5_3RepositoryFolders.CworkMainFormFolder CworkMainForm
        {
            get { return _cworkmainform; }
        }

        /// <summary>
        /// The ProprietesPourCnc1 folder.
        /// </summary>
        [RepositoryFolder("49817afb-eac2-41eb-a714-e2c9d8ceb817")]
        public virtual Sprint_9_5_3RepositoryFolders.ProprietesPourCnc1AppFolder ProprietesPourCnc1
        {
            get { return _proprietespourcnc1; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("322cb909-7998-4a84-9eaa-49f05469273b")]
        public virtual Sprint_9_5_3RepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The HEIDENHAINDNCConnectionsRWPermiss folder.
        /// </summary>
        [RepositoryFolder("97e5b2d8-dfd0-4917-8e69-1d0529cc29a8")]
        public virtual Sprint_9_5_3RepositoryFolders.HEIDENHAINDNCConnectionsRWPermissAppFolder HEIDENHAINDNCConnectionsRWPermiss
        {
            get { return _heidenhaindncconnectionsrwpermiss; }
        }

        /// <summary>
        /// The WelcomeToTheAddConnectionWizard folder.
        /// </summary>
        [RepositoryFolder("3ffdd1b6-d0f4-4e72-b587-f143d4537673")]
        public virtual Sprint_9_5_3RepositoryFolders.WelcomeToTheAddConnectionWizardAppFolder WelcomeToTheAddConnectionWizard
        {
            get { return _welcometotheaddconnectionwizard; }
        }

        /// <summary>
        /// The DeleteConnectionWizard folder.
        /// </summary>
        [RepositoryFolder("e3c646d3-8a97-428b-a6ab-b8e6e46fdd91")]
        public virtual Sprint_9_5_3RepositoryFolders.DeleteConnectionWizardAppFolder DeleteConnectionWizard
        {
            get { return _deleteconnectionwizard; }
        }

        /// <summary>
        /// The Name folder.
        /// </summary>
        [RepositoryFolder("8c6a408d-e546-477d-96fc-e5ac34fde5c2")]
        public virtual Sprint_9_5_3RepositoryFolders.NameAppFolder Name
        {
            get { return _name; }
        }

        /// <summary>
        /// The CNCType folder.
        /// </summary>
        [RepositoryFolder("84dd922b-05a8-4d64-9c99-855d64d482f1")]
        public virtual Sprint_9_5_3RepositoryFolders.CNCTypeAppFolder CNCType
        {
            get { return _cnctype; }
        }

        /// <summary>
        /// The CWork2021953DEV folder.
        /// </summary>
        [RepositoryFolder("1fade144-1d48-4779-8875-a46104964742")]
        public virtual Sprint_9_5_3RepositoryFolders.CWork2021953DEVAppFolder CWork2021953DEV
        {
            get { return _cwork2021953dev; }
        }

        /// <summary>
        /// The AddConnectionWizard folder.
        /// </summary>
        [RepositoryFolder("77f0ec7e-a78d-45f2-9a27-fefc9a571ab2")]
        public virtual Sprint_9_5_3RepositoryFolders.AddConnectionWizardAppFolder AddConnectionWizard
        {
            get { return _addconnectionwizard; }
        }

        /// <summary>
        /// The VersionsDeDocument folder.
        /// </summary>
        [RepositoryFolder("8b466d92-92a8-4825-8cc6-a167c62a4ada")]
        public virtual Sprint_9_5_3RepositoryFolders.VersionsDeDocumentAppFolder VersionsDeDocument
        {
            get { return _versionsdedocument; }
        }

        /// <summary>
        /// The EnregistrerSous folder.
        /// </summary>
        [RepositoryFolder("d3d10f68-357c-4d25-a423-36293e79effe")]
        public virtual Sprint_9_5_3RepositoryFolders.EnregistrerSousAppFolder EnregistrerSous
        {
            get { return _enregistrersous; }
        }

        /// <summary>
        /// The Cwork folder.
        /// </summary>
        [RepositoryFolder("67781c30-0dbc-43ff-80d9-2ef825143f19")]
        public virtual Sprint_9_5_3RepositoryFolders.CworkAppFolder Cwork
        {
            get { return _cwork; }
        }

        /// <summary>
        /// The TestPdfTravailMicrosoftEdge folder.
        /// </summary>
        [RepositoryFolder("54cc6448-5100-4dab-b399-fef986057902")]
        public virtual Sprint_9_5_3RepositoryFolders.TestPdfTravailMicrosoftEdgeAppFolder TestPdfTravailMicrosoftEdge
        {
            get { return _testpdftravailmicrosoftedge; }
        }

        /// <summary>
        /// The Cwork2024983DEV folder.
        /// </summary>
        [RepositoryFolder("c78b5bd5-bad5-46ca-b813-c49e6b90339f")]
        public virtual Sprint_9_5_3RepositoryFolders.Cwork2024983DEVAppFolder Cwork2024983DEV
        {
            get { return _cwork2024983dev; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Sprint_9_5_3RepositoryFolders
    {
        /// <summary>
        /// The CworkMainForm1AppFolder folder.
        /// </summary>
        [RepositoryFolder("4ca955be-f314-4b5a-8c37-17773175b419")]
        public partial class CworkMainForm1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cnc1Info;

            /// <summary>
            /// Creates a new CworkMainForm1  folder.
            /// </summary>
            public CworkMainForm1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("CworkMainForm1", "/form[@controlname='CworkMainForm']", parentFolder, 30000, null, false, "4ca955be-f314-4b5a-8c37-17773175b419", "")
            {
                _cnc1Info = new RepoItemInfo(this, "Cnc1", "element[@controlname='pages']//element[@controlname='StationsTiles']/rawtext[@rawtext='Cnc-1']", "", 30000, null, "d1195cd2-39d4-4069-85c5-f2961c0255da");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4ca955be-f314-4b5a-8c37-17773175b419")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4ca955be-f314-4b5a-8c37-17773175b419")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cnc1 item.
            /// </summary>
            [RepositoryItem("d1195cd2-39d4-4069-85c5-f2961c0255da")]
            public virtual Ranorex.RawText Cnc1
            {
                get
                {
                    return _cnc1Info.CreateAdapter<Ranorex.RawText>(true);
                }
            }

            /// <summary>
            /// The Cnc1 item info.
            /// </summary>
            [RepositoryItemInfo("d1195cd2-39d4-4069-85c5-f2961c0255da")]
            public virtual RepoItemInfo Cnc1Info
            {
                get
                {
                    return _cnc1Info;
                }
            }
        }

        /// <summary>
        /// The CworkMainFormFolder folder.
        /// </summary>
        [RepositoryFolder("4de63147-de44-4a47-b172-941b96d2e18f")]
        public partial class CworkMainFormFolder : RepoGenBaseFolder
        {
            Sprint_9_5_3RepositoryFolders.CWork202195AppFolder _cwork202195;

            /// <summary>
            /// Creates a new CworkMainForm  folder.
            /// </summary>
            public CworkMainFormFolder(RepoGenBaseFolder parentFolder) :
                    base("CworkMainForm", "", parentFolder, 0, null, false, "4de63147-de44-4a47-b172-941b96d2e18f", "")
            {
                _cwork202195 = new Sprint_9_5_3RepositoryFolders.CWork202195AppFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4de63147-de44-4a47-b172-941b96d2e18f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CWork202195 folder.
            /// </summary>
            [RepositoryFolder("2cc2deee-b518-4a8f-b116-2b82192a7b58")]
            public virtual Sprint_9_5_3RepositoryFolders.CWork202195AppFolder CWork202195
            {
                get { return _cwork202195; }
            }
        }

        /// <summary>
        /// The CWork202195AppFolder folder.
        /// </summary>
        [RepositoryFolder("2cc2deee-b518-4a8f-b116-2b82192a7b58")]
        public partial class CWork202195AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _bpropertyInfo;

            /// <summary>
            /// Creates a new CWork202195  folder.
            /// </summary>
            public CWork202195AppFolder(RepoGenBaseFolder parentFolder) :
                    base("CWork202195", "/form[@name='CworkMainForm']", parentFolder, 30000, null, true, "2cc2deee-b518-4a8f-b116-2b82192a7b58", "")
            {
                _bpropertyInfo = new RepoItemInfo(this, "BProperty", "element[@name='pages']/?/?/form[@name='CncViewForm']//element[@name='bProperty']", "", 30000, null, "e08a8b15-3ec7-425c-9a9f-48bb0478af59");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2cc2deee-b518-4a8f-b116-2b82192a7b58")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2cc2deee-b518-4a8f-b116-2b82192a7b58")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BProperty item.
            /// </summary>
            [RepositoryItem("e08a8b15-3ec7-425c-9a9f-48bb0478af59")]
            public virtual Ranorex.Unknown BProperty
            {
                get
                {
                    return _bpropertyInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BProperty item info.
            /// </summary>
            [RepositoryItemInfo("e08a8b15-3ec7-425c-9a9f-48bb0478af59")]
            public virtual RepoItemInfo BPropertyInfo
            {
                get
                {
                    return _bpropertyInfo;
                }
            }
        }

        /// <summary>
        /// The ProprietesPourCnc1AppFolder folder.
        /// </summary>
        [RepositoryFolder("49817afb-eac2-41eb-a714-e2c9d8ceb817")]
        public partial class ProprietesPourCnc1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _heidcomInfo;
            RepoItemInfo _collectedevenementsInfo;
            RepoItemInfo _activerlacollectedesalarmesInfo;
            RepoItemInfo _somebuttonInfo;
            RepoItemInfo _cbalarmmodeInfo;
            RepoItemInfo _buttonappliquerInfo;
            RepoItemInfo _activerlacollectedesprogrammescouraInfo;
            RepoItemInfo _somebutton1Info;
            RepoItemInfo _cbprogmodeInfo;
            RepoItemInfo _configurerInfo;
            RepoItemInfo _activerlacollectedesprogrammesencoInfo;
            RepoItemInfo _somebutton2Info;
            RepoItemInfo _cbrunningprgmodeInfo;

            /// <summary>
            /// Creates a new ProprietesPourCnc1  folder.
            /// </summary>
            public ProprietesPourCnc1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProprietesPourCnc1", "/form[@name='CncOptionsForm']", parentFolder, 30000, null, false, "49817afb-eac2-41eb-a714-e2c9d8ceb817", "")
            {
                _heidcomInfo = new RepoItemInfo(this, "HEIDCOM", "?/?/tree[@name='tvCategory']/?/?/treeitem[@text='HEID COM']", "", 30000, null, "81b12305-d9d6-4841-bb5e-6cc127adabdb");
                _collectedevenementsInfo = new RepoItemInfo(this, "CollecteDevenements", "?/?/tree[@name='tvCategory']/?/?/treeitem[@text='Collecte d''événements']", "", 30000, null, "4e819e40-ec14-4ff1-85ff-769a9f0b6e6c");
                _activerlacollectedesalarmesInfo = new RepoItemInfo(this, "ActiverLaCollecteDesAlarmes", "container[@name='ContainerPanel']/?/?/container[@name='TabSheet11']//container[@name='TabSheet8']/checkbox[@name='ckEnableAlarmCollect']", "", 30000, null, "70f9a69a-fc19-48da-89fb-e4497c0c1671");
                _somebuttonInfo = new RepoItemInfo(this, "SomeButton", ".//container[@name='TabSheet11']//container[@name='TabSheet8']/combobox[@name='cbAlarmMode']/button[@text='>']", "", 30000, null, "2feb6e56-62b2-43e3-bf38-09cfc39b3113");
                _cbalarmmodeInfo = new RepoItemInfo(this, "CbAlarmMode", "container[@name='ContainerPanel']/?/?/container[@name='TabSheet11']//container[@name='TabSheet8']/combobox[@name='cbAlarmMode']", "", 30000, null, "8e392a0e-d79b-433b-8cfe-1bca09961842");
                _buttonappliquerInfo = new RepoItemInfo(this, "ButtonAppliquer", "?/?/button[@name='bOK']", "", 30000, null, "63a8b059-2598-4c1b-9f99-86d896a26242");
                _activerlacollectedesprogrammescouraInfo = new RepoItemInfo(this, "ActiverLaCollecteDesProgrammesCoura", "container[@name='ContainerPanel']/?/?/container[@name='TabSheet11']//container[@name='TabSheet8']/checkbox[@name='ckEnableProgCollect']", "", 30000, null, "7cbf1785-984d-481e-aad5-4d8c18325c02");
                _somebutton1Info = new RepoItemInfo(this, "SomeButton1", ".//container[@name='TabSheet11']//container[@name='TabSheet8']/combobox[@name='cbProgMode']/button[@text='>']", "", 30000, null, "5ba80e9d-fb2c-4d4b-8a2a-0073d9bf94bd");
                _cbprogmodeInfo = new RepoItemInfo(this, "CbProgMode", "container[@name='ContainerPanel']/?/?/container[@name='TabSheet11']//container[@name='TabSheet8']/combobox[@name='cbProgMode']", "", 30000, null, "a8f1a9a5-eb71-400d-a887-a0bd9e1fca15");
                _configurerInfo = new RepoItemInfo(this, "Configurer", "container[@name='ContainerPanel']/?/?/container[@name='TabSheet11']//container[@name='TabSheet10']/button[@name='btnHeidComConfig']", "", 30000, null, "ba259c9f-1c72-4063-825e-b1c00ac06d60");
                _activerlacollectedesprogrammesencoInfo = new RepoItemInfo(this, "ActiverLaCollecteDesProgrammesEnCo", "container[@name='ContainerPanel']/?/?/container[@name='TabSheet11']//container[@name='TabSheet8']/checkbox[@name>'ckEnableRunningProgCollec']", "", 30000, null, "30ced6fe-6d08-4b8b-b9cf-94d334593ca5");
                _somebutton2Info = new RepoItemInfo(this, "SomeButton2", ".//container[@name='TabSheet11']//container[@name='TabSheet8']/combobox[@name='cbRunningPrgMode']/button[@text='>']", "", 30000, null, "5a60efe3-8f5f-401f-8ef3-95a86b5b0049");
                _cbrunningprgmodeInfo = new RepoItemInfo(this, "CbRunningPrgMode", "container[@name='ContainerPanel']/?/?/container[@name='TabSheet11']//container[@name='TabSheet8']/combobox[@name='cbRunningPrgMode']", "", 30000, null, "fb3a6c72-25e7-42a7-91b7-fda9aad231ea");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("49817afb-eac2-41eb-a714-e2c9d8ceb817")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("49817afb-eac2-41eb-a714-e2c9d8ceb817")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HEIDCOM item.
            /// </summary>
            [RepositoryItem("81b12305-d9d6-4841-bb5e-6cc127adabdb")]
            public virtual Ranorex.TreeItem HEIDCOM
            {
                get
                {
                    return _heidcomInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The HEIDCOM item info.
            /// </summary>
            [RepositoryItemInfo("81b12305-d9d6-4841-bb5e-6cc127adabdb")]
            public virtual RepoItemInfo HEIDCOMInfo
            {
                get
                {
                    return _heidcomInfo;
                }
            }

            /// <summary>
            /// The CollecteDevenements item.
            /// </summary>
            [RepositoryItem("4e819e40-ec14-4ff1-85ff-769a9f0b6e6c")]
            public virtual Ranorex.TreeItem CollecteDevenements
            {
                get
                {
                    return _collectedevenementsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The CollecteDevenements item info.
            /// </summary>
            [RepositoryItemInfo("4e819e40-ec14-4ff1-85ff-769a9f0b6e6c")]
            public virtual RepoItemInfo CollecteDevenementsInfo
            {
                get
                {
                    return _collectedevenementsInfo;
                }
            }

            /// <summary>
            /// The ActiverLaCollecteDesAlarmes item.
            /// </summary>
            [RepositoryItem("70f9a69a-fc19-48da-89fb-e4497c0c1671")]
            public virtual Ranorex.CheckBox ActiverLaCollecteDesAlarmes
            {
                get
                {
                    return _activerlacollectedesalarmesInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ActiverLaCollecteDesAlarmes item info.
            /// </summary>
            [RepositoryItemInfo("70f9a69a-fc19-48da-89fb-e4497c0c1671")]
            public virtual RepoItemInfo ActiverLaCollecteDesAlarmesInfo
            {
                get
                {
                    return _activerlacollectedesalarmesInfo;
                }
            }

            /// <summary>
            /// The SomeButton item.
            /// </summary>
            [RepositoryItem("2feb6e56-62b2-43e3-bf38-09cfc39b3113")]
            public virtual Ranorex.Button SomeButton
            {
                get
                {
                    return _somebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton item info.
            /// </summary>
            [RepositoryItemInfo("2feb6e56-62b2-43e3-bf38-09cfc39b3113")]
            public virtual RepoItemInfo SomeButtonInfo
            {
                get
                {
                    return _somebuttonInfo;
                }
            }

            /// <summary>
            /// The CbAlarmMode item.
            /// </summary>
            [RepositoryItem("8e392a0e-d79b-433b-8cfe-1bca09961842")]
            public virtual Ranorex.ComboBox CbAlarmMode
            {
                get
                {
                    return _cbalarmmodeInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CbAlarmMode item info.
            /// </summary>
            [RepositoryItemInfo("8e392a0e-d79b-433b-8cfe-1bca09961842")]
            public virtual RepoItemInfo CbAlarmModeInfo
            {
                get
                {
                    return _cbalarmmodeInfo;
                }
            }

            /// <summary>
            /// The ButtonAppliquer item.
            /// </summary>
            [RepositoryItem("63a8b059-2598-4c1b-9f99-86d896a26242")]
            public virtual Ranorex.Button ButtonAppliquer
            {
                get
                {
                    return _buttonappliquerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAppliquer item info.
            /// </summary>
            [RepositoryItemInfo("63a8b059-2598-4c1b-9f99-86d896a26242")]
            public virtual RepoItemInfo ButtonAppliquerInfo
            {
                get
                {
                    return _buttonappliquerInfo;
                }
            }

            /// <summary>
            /// The ActiverLaCollecteDesProgrammesCoura item.
            /// </summary>
            [RepositoryItem("7cbf1785-984d-481e-aad5-4d8c18325c02")]
            public virtual Ranorex.CheckBox ActiverLaCollecteDesProgrammesCoura
            {
                get
                {
                    return _activerlacollectedesprogrammescouraInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ActiverLaCollecteDesProgrammesCoura item info.
            /// </summary>
            [RepositoryItemInfo("7cbf1785-984d-481e-aad5-4d8c18325c02")]
            public virtual RepoItemInfo ActiverLaCollecteDesProgrammesCouraInfo
            {
                get
                {
                    return _activerlacollectedesprogrammescouraInfo;
                }
            }

            /// <summary>
            /// The SomeButton1 item.
            /// </summary>
            [RepositoryItem("5ba80e9d-fb2c-4d4b-8a2a-0073d9bf94bd")]
            public virtual Ranorex.Button SomeButton1
            {
                get
                {
                    return _somebutton1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton1 item info.
            /// </summary>
            [RepositoryItemInfo("5ba80e9d-fb2c-4d4b-8a2a-0073d9bf94bd")]
            public virtual RepoItemInfo SomeButton1Info
            {
                get
                {
                    return _somebutton1Info;
                }
            }

            /// <summary>
            /// The CbProgMode item.
            /// </summary>
            [RepositoryItem("a8f1a9a5-eb71-400d-a887-a0bd9e1fca15")]
            public virtual Ranorex.ComboBox CbProgMode
            {
                get
                {
                    return _cbprogmodeInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CbProgMode item info.
            /// </summary>
            [RepositoryItemInfo("a8f1a9a5-eb71-400d-a887-a0bd9e1fca15")]
            public virtual RepoItemInfo CbProgModeInfo
            {
                get
                {
                    return _cbprogmodeInfo;
                }
            }

            /// <summary>
            /// The Configurer item.
            /// </summary>
            [RepositoryItem("ba259c9f-1c72-4063-825e-b1c00ac06d60")]
            public virtual Ranorex.Button Configurer
            {
                get
                {
                    return _configurerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Configurer item info.
            /// </summary>
            [RepositoryItemInfo("ba259c9f-1c72-4063-825e-b1c00ac06d60")]
            public virtual RepoItemInfo ConfigurerInfo
            {
                get
                {
                    return _configurerInfo;
                }
            }

            /// <summary>
            /// The ActiverLaCollecteDesProgrammesEnCo item.
            /// </summary>
            [RepositoryItem("30ced6fe-6d08-4b8b-b9cf-94d334593ca5")]
            public virtual Ranorex.CheckBox ActiverLaCollecteDesProgrammesEnCo
            {
                get
                {
                    return _activerlacollectedesprogrammesencoInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ActiverLaCollecteDesProgrammesEnCo item info.
            /// </summary>
            [RepositoryItemInfo("30ced6fe-6d08-4b8b-b9cf-94d334593ca5")]
            public virtual RepoItemInfo ActiverLaCollecteDesProgrammesEnCoInfo
            {
                get
                {
                    return _activerlacollectedesprogrammesencoInfo;
                }
            }

            /// <summary>
            /// The SomeButton2 item.
            /// </summary>
            [RepositoryItem("5a60efe3-8f5f-401f-8ef3-95a86b5b0049")]
            public virtual Ranorex.Button SomeButton2
            {
                get
                {
                    return _somebutton2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton2 item info.
            /// </summary>
            [RepositoryItemInfo("5a60efe3-8f5f-401f-8ef3-95a86b5b0049")]
            public virtual RepoItemInfo SomeButton2Info
            {
                get
                {
                    return _somebutton2Info;
                }
            }

            /// <summary>
            /// The CbRunningPrgMode item.
            /// </summary>
            [RepositoryItem("fb3a6c72-25e7-42a7-91b7-fda9aad231ea")]
            public virtual Ranorex.ComboBox CbRunningPrgMode
            {
                get
                {
                    return _cbrunningprgmodeInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CbRunningPrgMode item info.
            /// </summary>
            [RepositoryItemInfo("fb3a6c72-25e7-42a7-91b7-fda9aad231ea")]
            public virtual RepoItemInfo CbRunningPrgModeInfo
            {
                get
                {
                    return _cbrunningprgmodeInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("322cb909-7998-4a84-9eaa-49f05469273b")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _viaheidcomInfo;
            RepoItemInfo _tnc6xxInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, false, "322cb909-7998-4a84-9eaa-49f05469273b", "")
            {
                _viaheidcomInfo = new RepoItemInfo(this, "ViaHeidCOM", "listitem[@text='Via Heid COM']", "", 30000, null, "1134fc9a-d373-4db2-9e8b-3353701f6deb");
                _tnc6xxInfo = new RepoItemInfo(this, "TNC6xx", "listitem[@text='TNC 6xx']", "", 30000, null, "97493730-1a96-4d72-8e26-ce2edfbdbd26");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("322cb909-7998-4a84-9eaa-49f05469273b")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("322cb909-7998-4a84-9eaa-49f05469273b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ViaHeidCOM item.
            /// </summary>
            [RepositoryItem("1134fc9a-d373-4db2-9e8b-3353701f6deb")]
            public virtual Ranorex.ListItem ViaHeidCOM
            {
                get
                {
                    return _viaheidcomInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ViaHeidCOM item info.
            /// </summary>
            [RepositoryItemInfo("1134fc9a-d373-4db2-9e8b-3353701f6deb")]
            public virtual RepoItemInfo ViaHeidCOMInfo
            {
                get
                {
                    return _viaheidcomInfo;
                }
            }

            /// <summary>
            /// The TNC6xx item.
            /// </summary>
            [RepositoryItem("97493730-1a96-4d72-8e26-ce2edfbdbd26")]
            public virtual Ranorex.ListItem TNC6xx
            {
                get
                {
                    return _tnc6xxInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The TNC6xx item info.
            /// </summary>
            [RepositoryItemInfo("97493730-1a96-4d72-8e26-ce2edfbdbd26")]
            public virtual RepoItemInfo TNC6xxInfo
            {
                get
                {
                    return _tnc6xxInfo;
                }
            }
        }

        /// <summary>
        /// The HEIDENHAINDNCConnectionsRWPermissAppFolder folder.
        /// </summary>
        [RepositoryFolder("97e5b2d8-dfd0-4917-8e69-1d0529cc29a8")]
        public partial class HEIDENHAINDNCConnectionsRWPermissAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonaddInfo;
            RepoItemInfo _cellcw1Info;
            RepoItemInfo _closeInfo;
            RepoItemInfo _buttonremoveInfo;

            /// <summary>
            /// Creates a new HEIDENHAINDNCConnectionsRWPermiss  folder.
            /// </summary>
            public HEIDENHAINDNCConnectionsRWPermissAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HEIDENHAINDNCConnectionsRWPermiss", "/form[@title>'HEIDENHAIN DNC Connections']", parentFolder, 30000, null, false, "97e5b2d8-dfd0-4917-8e69-1d0529cc29a8", "")
            {
                _buttonaddInfo = new RepoItemInfo(this, "ButtonAdd", "button[@text='&Add...']", "", 30000, null, "c087b8fa-3b54-480f-9f6b-c3fea603adef");
                _cellcw1Info = new RepoItemInfo(this, "CellCW1", "table[@controlid='301']/?/?/cell[@text='CW1']", "", 30000, null, "4dbaa00c-7a9d-4691-9da2-b197a8550a93");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Fermer']", "", 30000, null, "abce4403-e6c0-4fab-b674-e7525342fba8");
                _buttonremoveInfo = new RepoItemInfo(this, "ButtonRemove", "button[@text='&Remove...']", "", 30000, null, "77d4772c-7ee3-4b0b-b521-3fcc1bdc0063");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("97e5b2d8-dfd0-4917-8e69-1d0529cc29a8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("97e5b2d8-dfd0-4917-8e69-1d0529cc29a8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonAdd item.
            /// </summary>
            [RepositoryItem("c087b8fa-3b54-480f-9f6b-c3fea603adef")]
            public virtual Ranorex.Button ButtonAdd
            {
                get
                {
                    return _buttonaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAdd item info.
            /// </summary>
            [RepositoryItemInfo("c087b8fa-3b54-480f-9f6b-c3fea603adef")]
            public virtual RepoItemInfo ButtonAddInfo
            {
                get
                {
                    return _buttonaddInfo;
                }
            }

            /// <summary>
            /// The CellCW1 item.
            /// </summary>
            [RepositoryItem("4dbaa00c-7a9d-4691-9da2-b197a8550a93")]
            public virtual Ranorex.Cell CellCW1
            {
                get
                {
                    return _cellcw1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellCW1 item info.
            /// </summary>
            [RepositoryItemInfo("4dbaa00c-7a9d-4691-9da2-b197a8550a93")]
            public virtual RepoItemInfo CellCW1Info
            {
                get
                {
                    return _cellcw1Info;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("abce4403-e6c0-4fab-b674-e7525342fba8")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("abce4403-e6c0-4fab-b674-e7525342fba8")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The ButtonRemove item.
            /// </summary>
            [RepositoryItem("77d4772c-7ee3-4b0b-b521-3fcc1bdc0063")]
            public virtual Ranorex.Button ButtonRemove
            {
                get
                {
                    return _buttonremoveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonRemove item info.
            /// </summary>
            [RepositoryItemInfo("77d4772c-7ee3-4b0b-b521-3fcc1bdc0063")]
            public virtual RepoItemInfo ButtonRemoveInfo
            {
                get
                {
                    return _buttonremoveInfo;
                }
            }
        }

        /// <summary>
        /// The WelcomeToTheAddConnectionWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("3ffdd1b6-d0f4-4e72-b587-f143d4537673")]
        public partial class WelcomeToTheAddConnectionWizardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonnextInfo;
            RepoItemInfo _text354Info;

            /// <summary>
            /// Creates a new WelcomeToTheAddConnectionWizard  folder.
            /// </summary>
            public WelcomeToTheAddConnectionWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WelcomeToTheAddConnectionWizard", "/form[@title>'Welcome to the Add Connection']", parentFolder, 30000, null, true, "3ffdd1b6-d0f4-4e72-b587-f143d4537673", "")
            {
                _buttonnextInfo = new RepoItemInfo(this, "ButtonNext", "button[@text='&Suivant >']", "", 30000, null, "5bb1fa00-95b5-41fc-ba94-c490641988f1");
                _text354Info = new RepoItemInfo(this, "Text354", "?/?/text[@controlid='354']", "", 30000, null, "b6120b62-27e4-4885-bf30-51412c8909bd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3ffdd1b6-d0f4-4e72-b587-f143d4537673")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3ffdd1b6-d0f4-4e72-b587-f143d4537673")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonNext item.
            /// </summary>
            [RepositoryItem("5bb1fa00-95b5-41fc-ba94-c490641988f1")]
            public virtual Ranorex.Button ButtonNext
            {
                get
                {
                    return _buttonnextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNext item info.
            /// </summary>
            [RepositoryItemInfo("5bb1fa00-95b5-41fc-ba94-c490641988f1")]
            public virtual RepoItemInfo ButtonNextInfo
            {
                get
                {
                    return _buttonnextInfo;
                }
            }

            /// <summary>
            /// The Text354 item.
            /// </summary>
            [RepositoryItem("b6120b62-27e4-4885-bf30-51412c8909bd")]
            public virtual Ranorex.Text Text354
            {
                get
                {
                    return _text354Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text354 item info.
            /// </summary>
            [RepositoryItemInfo("b6120b62-27e4-4885-bf30-51412c8909bd")]
            public virtual RepoItemInfo Text354Info
            {
                get
                {
                    return _text354Info;
                }
            }
        }

        /// <summary>
        /// The DeleteConnectionWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("e3c646d3-8a97-428b-a6ab-b8e6e46fdd91")]
        public partial class DeleteConnectionWizardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new DeleteConnectionWizard  folder.
            /// </summary>
            public DeleteConnectionWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DeleteConnectionWizard", "/form[@title='Delete Connection Wizard']", parentFolder, 30000, null, false, "e3c646d3-8a97-428b-a6ab-b8e6e46fdd91", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", "", 30000, null, "7e756c80-1b11-4eca-9f60-41534a233039");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e3c646d3-8a97-428b-a6ab-b8e6e46fdd91")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e3c646d3-8a97-428b-a6ab-b8e6e46fdd91")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("7e756c80-1b11-4eca-9f60-41534a233039")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("7e756c80-1b11-4eca-9f60-41534a233039")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The NameAppFolder folder.
        /// </summary>
        [RepositoryFolder("8c6a408d-e546-477d-96fc-e5ac34fde5c2")]
        public partial class NameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text354Info;

            /// <summary>
            /// Creates a new Name  folder.
            /// </summary>
            public NameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Name", "/form[@title='Name']", parentFolder, 30000, null, false, "8c6a408d-e546-477d-96fc-e5ac34fde5c2", "")
            {
                _text354Info = new RepoItemInfo(this, "Text354", "?/?/text[@controlid='354']", "", 30000, null, "6b325e26-78e6-4441-9238-5e6cfb69a84b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8c6a408d-e546-477d-96fc-e5ac34fde5c2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8c6a408d-e546-477d-96fc-e5ac34fde5c2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text354 item.
            /// </summary>
            [RepositoryItem("6b325e26-78e6-4441-9238-5e6cfb69a84b")]
            public virtual Ranorex.Text Text354
            {
                get
                {
                    return _text354Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text354 item info.
            /// </summary>
            [RepositoryItemInfo("6b325e26-78e6-4441-9238-5e6cfb69a84b")]
            public virtual RepoItemInfo Text354Info
            {
                get
                {
                    return _text354Info;
                }
            }
        }

        /// <summary>
        /// The CNCTypeAppFolder folder.
        /// </summary>
        [RepositoryFolder("84dd922b-05a8-4d64-9c99-855d64d482f1")]
        public partial class CNCTypeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _somebuttonInfo;
            RepoItemInfo _buttonnextInfo;

            /// <summary>
            /// Creates a new CNCType  folder.
            /// </summary>
            public CNCTypeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CNCType", "/form[@title='CNC Type']", parentFolder, 30000, null, false, "84dd922b-05a8-4d64-9c99-855d64d482f1", "")
            {
                _somebuttonInfo = new RepoItemInfo(this, "SomeButton", "?/?/combobox[@controlid='347']/button[@text='>']", "", 30000, null, "cb937858-b807-43ca-a265-7d73c9fedc5a");
                _buttonnextInfo = new RepoItemInfo(this, "ButtonNext", "button[@text='&Suivant >']", "", 30000, null, "884234cf-462a-4548-976d-bc6f3c5b46b3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("84dd922b-05a8-4d64-9c99-855d64d482f1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("84dd922b-05a8-4d64-9c99-855d64d482f1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeButton item.
            /// </summary>
            [RepositoryItem("cb937858-b807-43ca-a265-7d73c9fedc5a")]
            public virtual Ranorex.Button SomeButton
            {
                get
                {
                    return _somebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton item info.
            /// </summary>
            [RepositoryItemInfo("cb937858-b807-43ca-a265-7d73c9fedc5a")]
            public virtual RepoItemInfo SomeButtonInfo
            {
                get
                {
                    return _somebuttonInfo;
                }
            }

            /// <summary>
            /// The ButtonNext item.
            /// </summary>
            [RepositoryItem("884234cf-462a-4548-976d-bc6f3c5b46b3")]
            public virtual Ranorex.Button ButtonNext
            {
                get
                {
                    return _buttonnextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNext item info.
            /// </summary>
            [RepositoryItemInfo("884234cf-462a-4548-976d-bc6f3c5b46b3")]
            public virtual RepoItemInfo ButtonNextInfo
            {
                get
                {
                    return _buttonnextInfo;
                }
            }
        }

        /// <summary>
        /// The CWork2021953DEVAppFolder folder.
        /// </summary>
        [RepositoryFolder("1fade144-1d48-4779-8875-a46104964742")]
        public partial class CWork2021953DEVAppFolder : RepoGenBaseFolder
        {
            Sprint_9_5_3RepositoryFolders.ChoixDateFolder _choixdate;
            RepoItemInfo _cnc1Info;
            RepoItemInfo _bshowprogramInfo;
            RepoItemInfo _png1Info;
            RepoItemInfo _png2Info;
            RepoItemInfo _bcompareInfo;
            RepoItemInfo _bpdfInfo;
            RepoItemInfo _menuitemfichierInfo;
            RepoItemInfo _bcloseInfo;
            RepoItemInfo _bsingleselectInfo;
            RepoItemInfo _calendarday1Info;
            RepoItemInfo _calendarday3Info;
            SomeElement2InfoClass _someelement2Info;

            /// <summary>
            /// Creates a new CWork2021953DEV  folder.
            /// </summary>
            public CWork2021953DEVAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CWork2021953DEV", "/form[@name='CworkMainForm']", parentFolder, 30000, null, false, "1fade144-1d48-4779-8875-a46104964742", "")
            {
                _choixdate = new Sprint_9_5_3RepositoryFolders.ChoixDateFolder(this);
                _cnc1Info = new RepoItemInfo(this, "Cnc1", "element[@name='pages']/?/?/form[@name='CncViewForm']/?/?/rawtext[@rawtext='Cnc-1']", "", 30000, null, "0e3f4814-80be-4c90-8f02-cdeef46f3ad4");
                _bshowprogramInfo = new RepoItemInfo(this, "BShowProgram", "element[@name='pages']/?/?/form[@name='CncViewForm']//element[@name='bShowProgram']", "", 30000, null, "ba5c2bab-a53b-40c3-a59c-8f9b25840eab");
                _png1Info = new RepoItemInfo(this, "Png1", ".//form[@name='DBViewForm']/?/?/list[@name='PartsView']/row[@name='png1']/cell[@name='png1']", "", 30000, null, "98b76f62-1d64-4c34-a70c-bffc55d5fd86");
                _png2Info = new RepoItemInfo(this, "Png2", ".//form[@name='DBViewForm']/?/?/list[@name='PartsView']/row[@name='png2']/cell[@name='png2']", "", 30000, null, "b3cf4a1f-7951-4041-b208-ecac8671aded");
                _bcompareInfo = new RepoItemInfo(this, "BCompare", "element[@name='pages']/?/?/form[@name='DBViewForm']//element[@name='bCompare']", "", 30000, null, "78d70af3-51d4-4592-b1ff-1f491df0ea4c");
                _bpdfInfo = new RepoItemInfo(this, "BPdf", "element[@name='pages']/?/?/form[@name='DBCompareForm']//element[@name='bPdf']", "", 30000, null, "84144686-d3a2-49cd-8d33-9994a170c787");
                _menuitemfichierInfo = new RepoItemInfo(this, "MenuItemFichier", "?/?/menuitem[@name='mnFile']", "", 30000, null, "3250fd3f-c8f0-4d5a-8cda-155d335fe0d0");
                _bcloseInfo = new RepoItemInfo(this, "BClose", "element[@name='pages']/?/?/form[@name='DBCompareForm']//element[@name='bClose']", "", 30000, null, "1ddef188-987f-4551-8067-3ca8b1b3cb3f");
                _bsingleselectInfo = new RepoItemInfo(this, "BSingleSelect", "element[@name='pages']/?/?/form[@name='DBViewForm']//element[@name='bSingleSelect']", "", 30000, null, "c25510b8-52d9-4a58-8114-5d9cd00f6971");
                _calendarday1Info = new RepoItemInfo(this, "CalendarDay1", "element[@name='pages']/?/?/form[@name='StationHistoryForm']/container[@name='toolPanelDateSelect']/?/?/rawtext[@rawtext='1']", "", 30000, null, "fb684719-2858-4ff8-8eda-3690fdf67f00");
                _calendarday3Info = new RepoItemInfo(this, "CalendarDay3", "element[@name='pages']/?/?/form[@name='StationHistoryForm']/container[@name='toolPanelDateSelect']/?/?/rawtext[@rawtext='3']", "", 30000, null, "a98a9260-1b60-4834-909b-ee36863d008e");
                _someelement2Info = new SomeElement2InfoClass(this);
            }

            /// <summary>
            /// The SomeElement2InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("95414605-f45d-479b-ac15-7d38bba84707")]
            public class SomeElement2InfoClass : RepoItemInfo
            {
                /// <summary>
                /// SomeElement2InfoClass class constructor.
                /// </summary>
                public SomeElement2InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SomeElement2", ".//form[@name='StationHistoryForm']/container[@name='pnlMainView']/form[@name='HistoryTimelineView']/?/?/container[@name='scrollBox']/element[3]", 30000, null, "95414605-f45d-479b-ac15-7d38bba84707")
                { }

                /// <summary>
                /// Gets the Verify_D_60cf3d4b_rxlog1 item image.
                /// </summary>
                /// <returns>The Verify_D_60cf3d4b_rxlog1 image.</returns>
                [RepositoryImage("50def256-55e8-41ec-a8ca-254cd3fb2d13")]
                public CompressedImage GetVerify_D_60cf3d4b_rxlog1()
                {
                    return GetImage("50def256-55e8-41ec-a8ca-254cd3fb2d13");
                }

                /// <summary>
                /// Gets the Verify_D_60cf3d4b_rxlog1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("50def256-55e8-41ec-a8ca-254cd3fb2d13")]
                public CompressedImage GetVerify_D_60cf3d4b_rxlog1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("50def256-55e8-41ec-a8ca-254cd3fb2d13", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1fade144-1d48-4779-8875-a46104964742")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1fade144-1d48-4779-8875-a46104964742")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cnc1 item.
            /// </summary>
            [RepositoryItem("0e3f4814-80be-4c90-8f02-cdeef46f3ad4")]
            public virtual Ranorex.RawText Cnc1
            {
                get
                {
                    return _cnc1Info.CreateAdapter<Ranorex.RawText>(true);
                }
            }

            /// <summary>
            /// The Cnc1 item info.
            /// </summary>
            [RepositoryItemInfo("0e3f4814-80be-4c90-8f02-cdeef46f3ad4")]
            public virtual RepoItemInfo Cnc1Info
            {
                get
                {
                    return _cnc1Info;
                }
            }

            /// <summary>
            /// The BShowProgram item.
            /// </summary>
            [RepositoryItem("ba5c2bab-a53b-40c3-a59c-8f9b25840eab")]
            public virtual Ranorex.Unknown BShowProgram
            {
                get
                {
                    return _bshowprogramInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BShowProgram item info.
            /// </summary>
            [RepositoryItemInfo("ba5c2bab-a53b-40c3-a59c-8f9b25840eab")]
            public virtual RepoItemInfo BShowProgramInfo
            {
                get
                {
                    return _bshowprogramInfo;
                }
            }

            /// <summary>
            /// The Png1 item.
            /// </summary>
            [RepositoryItem("98b76f62-1d64-4c34-a70c-bffc55d5fd86")]
            public virtual Ranorex.Cell Png1
            {
                get
                {
                    return _png1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Png1 item info.
            /// </summary>
            [RepositoryItemInfo("98b76f62-1d64-4c34-a70c-bffc55d5fd86")]
            public virtual RepoItemInfo Png1Info
            {
                get
                {
                    return _png1Info;
                }
            }

            /// <summary>
            /// The Png2 item.
            /// </summary>
            [RepositoryItem("b3cf4a1f-7951-4041-b208-ecac8671aded")]
            public virtual Ranorex.Cell Png2
            {
                get
                {
                    return _png2Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Png2 item info.
            /// </summary>
            [RepositoryItemInfo("b3cf4a1f-7951-4041-b208-ecac8671aded")]
            public virtual RepoItemInfo Png2Info
            {
                get
                {
                    return _png2Info;
                }
            }

            /// <summary>
            /// The BCompare item.
            /// </summary>
            [RepositoryItem("78d70af3-51d4-4592-b1ff-1f491df0ea4c")]
            public virtual Ranorex.Unknown BCompare
            {
                get
                {
                    return _bcompareInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BCompare item info.
            /// </summary>
            [RepositoryItemInfo("78d70af3-51d4-4592-b1ff-1f491df0ea4c")]
            public virtual RepoItemInfo BCompareInfo
            {
                get
                {
                    return _bcompareInfo;
                }
            }

            /// <summary>
            /// The BPdf item.
            /// </summary>
            [RepositoryItem("84144686-d3a2-49cd-8d33-9994a170c787")]
            public virtual Ranorex.Unknown BPdf
            {
                get
                {
                    return _bpdfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BPdf item info.
            /// </summary>
            [RepositoryItemInfo("84144686-d3a2-49cd-8d33-9994a170c787")]
            public virtual RepoItemInfo BPdfInfo
            {
                get
                {
                    return _bpdfInfo;
                }
            }

            /// <summary>
            /// The MenuItemFichier item.
            /// </summary>
            [RepositoryItem("3250fd3f-c8f0-4d5a-8cda-155d335fe0d0")]
            public virtual Ranorex.MenuItem MenuItemFichier
            {
                get
                {
                    return _menuitemfichierInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemFichier item info.
            /// </summary>
            [RepositoryItemInfo("3250fd3f-c8f0-4d5a-8cda-155d335fe0d0")]
            public virtual RepoItemInfo MenuItemFichierInfo
            {
                get
                {
                    return _menuitemfichierInfo;
                }
            }

            /// <summary>
            /// The BClose item.
            /// </summary>
            [RepositoryItem("1ddef188-987f-4551-8067-3ca8b1b3cb3f")]
            public virtual Ranorex.Unknown BClose
            {
                get
                {
                    return _bcloseInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BClose item info.
            /// </summary>
            [RepositoryItemInfo("1ddef188-987f-4551-8067-3ca8b1b3cb3f")]
            public virtual RepoItemInfo BCloseInfo
            {
                get
                {
                    return _bcloseInfo;
                }
            }

            /// <summary>
            /// The BSingleSelect item.
            /// </summary>
            [RepositoryItem("c25510b8-52d9-4a58-8114-5d9cd00f6971")]
            public virtual Ranorex.Unknown BSingleSelect
            {
                get
                {
                    return _bsingleselectInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BSingleSelect item info.
            /// </summary>
            [RepositoryItemInfo("c25510b8-52d9-4a58-8114-5d9cd00f6971")]
            public virtual RepoItemInfo BSingleSelectInfo
            {
                get
                {
                    return _bsingleselectInfo;
                }
            }

            /// <summary>
            /// The CalendarDay1 item.
            /// </summary>
            [RepositoryItem("fb684719-2858-4ff8-8eda-3690fdf67f00")]
            public virtual Ranorex.RawText CalendarDay1
            {
                get
                {
                    return _calendarday1Info.CreateAdapter<Ranorex.RawText>(true);
                }
            }

            /// <summary>
            /// The CalendarDay1 item info.
            /// </summary>
            [RepositoryItemInfo("fb684719-2858-4ff8-8eda-3690fdf67f00")]
            public virtual RepoItemInfo CalendarDay1Info
            {
                get
                {
                    return _calendarday1Info;
                }
            }

            /// <summary>
            /// The CalendarDay3 item.
            /// </summary>
            [RepositoryItem("a98a9260-1b60-4834-909b-ee36863d008e")]
            public virtual Ranorex.RawText CalendarDay3
            {
                get
                {
                    return _calendarday3Info.CreateAdapter<Ranorex.RawText>(true);
                }
            }

            /// <summary>
            /// The CalendarDay3 item info.
            /// </summary>
            [RepositoryItemInfo("a98a9260-1b60-4834-909b-ee36863d008e")]
            public virtual RepoItemInfo CalendarDay3Info
            {
                get
                {
                    return _calendarday3Info;
                }
            }

            /// <summary>
            /// The SomeElement2 item.
            /// </summary>
            [RepositoryItem("95414605-f45d-479b-ac15-7d38bba84707")]
            public virtual Ranorex.Unknown SomeElement2
            {
                get
                {
                    return _someelement2Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement2 item info.
            /// </summary>
            [RepositoryItemInfo("95414605-f45d-479b-ac15-7d38bba84707")]
            public virtual SomeElement2InfoClass SomeElement2Info
            {
                get
                {
                    return _someelement2Info;
                }
            }

            /// <summary>
            /// The ChoixDate folder.
            /// </summary>
            [RepositoryFolder("f7e060ef-1a2a-448d-8c4d-b8c2f58c0c9d")]
            public virtual Sprint_9_5_3RepositoryFolders.ChoixDateFolder ChoixDate
            {
                get { return _choixdate; }
            }
        }

        /// <summary>
        /// The ChoixDateFolder folder.
        /// </summary>
        [RepositoryFolder("f7e060ef-1a2a-448d-8c4d-b8c2f58c0c9d")]
        public partial class ChoixDateFolder : RepoGenBaseFolder
        {
            RepoItemInfo _dtpfromInfo;
            RepoItemInfo _dtptoInfo;
            RepoItemInfo _bvalidecustomInfo;
            RepoItemInfo _btncustomInfo;

            /// <summary>
            /// Creates a new ChoixDate  folder.
            /// </summary>
            public ChoixDateFolder(RepoGenBaseFolder parentFolder) :
                    base("ChoixDate", ".//form[@name='StationHistoryForm']/container[@name='toolPanelDateSelect']", parentFolder, 30000, null, false, "f7e060ef-1a2a-448d-8c4d-b8c2f58c0c9d", "")
            {
                _dtpfromInfo = new RepoItemInfo(this, "DtpFrom", "?/?/datetime[@name='dtpFrom']", "", 30000, null, "40e12f6e-e324-4d17-bc7b-c898abdca999");
                _dtptoInfo = new RepoItemInfo(this, "DtpTo", "?/?/datetime[@name='dtpTo']", "", 30000, null, "1294b7bf-c366-488a-9d6a-71523e5f31d2");
                _bvalidecustomInfo = new RepoItemInfo(this, "BValideCustom", "?/?/element[@name='bValideCustom']", "", 30000, null, "bc05ed0b-5db1-40a6-987f-e643d8534d13");
                _btncustomInfo = new RepoItemInfo(this, "BtnCustom", "?/?/element[@name='btnCustom']", "", 30000, null, "a720646e-88d2-4f89-965d-3ee4a7351bc0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f7e060ef-1a2a-448d-8c4d-b8c2f58c0c9d")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f7e060ef-1a2a-448d-8c4d-b8c2f58c0c9d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DtpFrom item.
            /// </summary>
            [RepositoryItem("40e12f6e-e324-4d17-bc7b-c898abdca999")]
            public virtual Ranorex.DateTime DtpFrom
            {
                get
                {
                    return _dtpfromInfo.CreateAdapter<Ranorex.DateTime>(true);
                }
            }

            /// <summary>
            /// The DtpFrom item info.
            /// </summary>
            [RepositoryItemInfo("40e12f6e-e324-4d17-bc7b-c898abdca999")]
            public virtual RepoItemInfo DtpFromInfo
            {
                get
                {
                    return _dtpfromInfo;
                }
            }

            /// <summary>
            /// The DtpTo item.
            /// </summary>
            [RepositoryItem("1294b7bf-c366-488a-9d6a-71523e5f31d2")]
            public virtual Ranorex.DateTime DtpTo
            {
                get
                {
                    return _dtptoInfo.CreateAdapter<Ranorex.DateTime>(true);
                }
            }

            /// <summary>
            /// The DtpTo item info.
            /// </summary>
            [RepositoryItemInfo("1294b7bf-c366-488a-9d6a-71523e5f31d2")]
            public virtual RepoItemInfo DtpToInfo
            {
                get
                {
                    return _dtptoInfo;
                }
            }

            /// <summary>
            /// The BValideCustom item.
            /// </summary>
            [RepositoryItem("bc05ed0b-5db1-40a6-987f-e643d8534d13")]
            public virtual Ranorex.Unknown BValideCustom
            {
                get
                {
                    return _bvalidecustomInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BValideCustom item info.
            /// </summary>
            [RepositoryItemInfo("bc05ed0b-5db1-40a6-987f-e643d8534d13")]
            public virtual RepoItemInfo BValideCustomInfo
            {
                get
                {
                    return _bvalidecustomInfo;
                }
            }

            /// <summary>
            /// The BtnCustom item.
            /// </summary>
            [RepositoryItem("a720646e-88d2-4f89-965d-3ee4a7351bc0")]
            public virtual Ranorex.Unknown BtnCustom
            {
                get
                {
                    return _btncustomInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BtnCustom item info.
            /// </summary>
            [RepositoryItemInfo("a720646e-88d2-4f89-965d-3ee4a7351bc0")]
            public virtual RepoItemInfo BtnCustomInfo
            {
                get
                {
                    return _btncustomInfo;
                }
            }
        }

        /// <summary>
        /// The AddConnectionWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("77f0ec7e-a78d-45f2-9a27-fefc9a571ab2")]
        public partial class AddConnectionWizardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _terminerInfo;

            /// <summary>
            /// Creates a new AddConnectionWizard  folder.
            /// </summary>
            public AddConnectionWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddConnectionWizard", "/form[@title='Add Connection Wizard']", parentFolder, 30000, null, false, "77f0ec7e-a78d-45f2-9a27-fefc9a571ab2", "")
            {
                _terminerInfo = new RepoItemInfo(this, "Terminer", "button[@text='Terminer']", "", 30000, null, "7a934e0d-7650-4c9a-b011-b68f6610d64f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("77f0ec7e-a78d-45f2-9a27-fefc9a571ab2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("77f0ec7e-a78d-45f2-9a27-fefc9a571ab2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Terminer item.
            /// </summary>
            [RepositoryItem("7a934e0d-7650-4c9a-b011-b68f6610d64f")]
            public virtual Ranorex.Button Terminer
            {
                get
                {
                    return _terminerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Terminer item info.
            /// </summary>
            [RepositoryItemInfo("7a934e0d-7650-4c9a-b011-b68f6610d64f")]
            public virtual RepoItemInfo TerminerInfo
            {
                get
                {
                    return _terminerInfo;
                }
            }
        }

        /// <summary>
        /// The VersionsDeDocumentAppFolder folder.
        /// </summary>
        [RepositoryFolder("8b466d92-92a8-4825-8cc6-a167c62a4ada")]
        public partial class VersionsDeDocumentAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _bopenversionInfo;

            /// <summary>
            /// Creates a new VersionsDeDocument  folder.
            /// </summary>
            public VersionsDeDocumentAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VersionsDeDocument", "/form[@name='DBVersion']", parentFolder, 30000, null, false, "8b466d92-92a8-4825-8cc6-a167c62a4ada", "")
            {
                _bopenversionInfo = new RepoItemInfo(this, "BOpenVersion", "element[@name='paMain']//container[@name='Panel1']/element[@name='bOpenVersion']", "", 30000, null, "cd46e450-780c-4528-8634-2ede48457933");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8b466d92-92a8-4825-8cc6-a167c62a4ada")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8b466d92-92a8-4825-8cc6-a167c62a4ada")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BOpenVersion item.
            /// </summary>
            [RepositoryItem("cd46e450-780c-4528-8634-2ede48457933")]
            public virtual Ranorex.Unknown BOpenVersion
            {
                get
                {
                    return _bopenversionInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The BOpenVersion item info.
            /// </summary>
            [RepositoryItemInfo("cd46e450-780c-4528-8634-2ede48457933")]
            public virtual RepoItemInfo BOpenVersionInfo
            {
                get
                {
                    return _bopenversionInfo;
                }
            }
        }

        /// <summary>
        /// The EnregistrerSousAppFolder folder.
        /// </summary>
        [RepositoryFolder("d3d10f68-357c-4d25-a423-36293e79effe")]
        public partial class EnregistrerSousAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text1001Info;
            RepoItemInfo _buttonenregistrerInfo;

            /// <summary>
            /// Creates a new EnregistrerSous  folder.
            /// </summary>
            public EnregistrerSousAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EnregistrerSous", "/form[@title='Enregistrer sous']", parentFolder, 30000, null, false, "d3d10f68-357c-4d25-a423-36293e79effe", "")
            {
                _text1001Info = new RepoItemInfo(this, "Text1001", "element[@class='DUIViewWndClassName']//combobox[@class='ComboBox']/text[@controlid='1001']", "", 30000, null, "ff63424d-3dae-4480-96a4-b77c1ab0a71d");
                _buttonenregistrerInfo = new RepoItemInfo(this, "ButtonEnregistrer", "button[@text='&Enregistrer']", "", 30000, null, "a43ea824-9961-45cf-850f-874e48a16693");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d3d10f68-357c-4d25-a423-36293e79effe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d3d10f68-357c-4d25-a423-36293e79effe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("ff63424d-3dae-4480-96a4-b77c1ab0a71d")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("ff63424d-3dae-4480-96a4-b77c1ab0a71d")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }

            /// <summary>
            /// The ButtonEnregistrer item.
            /// </summary>
            [RepositoryItem("a43ea824-9961-45cf-850f-874e48a16693")]
            public virtual Ranorex.Button ButtonEnregistrer
            {
                get
                {
                    return _buttonenregistrerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonEnregistrer item info.
            /// </summary>
            [RepositoryItemInfo("a43ea824-9961-45cf-850f-874e48a16693")]
            public virtual RepoItemInfo ButtonEnregistrerInfo
            {
                get
                {
                    return _buttonenregistrerInfo;
                }
            }
        }

        /// <summary>
        /// The CworkAppFolder folder.
        /// </summary>
        [RepositoryFolder("67781c30-0dbc-43ff-80d9-2ef825143f19")]
        public partial class CworkAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuitemInfo;

            /// <summary>
            /// Creates a new Cwork  folder.
            /// </summary>
            public CworkAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Cwork", "/contextmenu[@processname='Cwork']", parentFolder, 30000, null, false, "67781c30-0dbc-43ff-80d9-2ef825143f19", "")
            {
                _menuitemInfo = new RepoItemInfo(this, "MenuItem", "contextmenu/menuitem[11]", "", 30000, null, "00416f8d-8067-43c7-8d65-e43cdb9f3c1c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("67781c30-0dbc-43ff-80d9-2ef825143f19")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("67781c30-0dbc-43ff-80d9-2ef825143f19")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItem item.
            /// </summary>
            [RepositoryItem("00416f8d-8067-43c7-8d65-e43cdb9f3c1c")]
            public virtual Ranorex.MenuItem MenuItem
            {
                get
                {
                    return _menuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItem item info.
            /// </summary>
            [RepositoryItemInfo("00416f8d-8067-43c7-8d65-e43cdb9f3c1c")]
            public virtual RepoItemInfo MenuItemInfo
            {
                get
                {
                    return _menuitemInfo;
                }
            }
        }

        /// <summary>
        /// The TestPdfTravailMicrosoftEdgeAppFolder folder.
        /// </summary>
        [RepositoryFolder("54cc6448-5100-4dab-b399-fef986057902")]
        public partial class TestPdfTravailMicrosoftEdgeAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new TestPdfTravailMicrosoftEdge  folder.
            /// </summary>
            public TestPdfTravailMicrosoftEdgeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TestPdfTravailMicrosoftEdge", "/form[@title>'Test.pdf']", parentFolder, 30000, null, false, "54cc6448-5100-4dab-b399-fef986057902", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("54cc6448-5100-4dab-b399-fef986057902")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("54cc6448-5100-4dab-b399-fef986057902")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The Cwork2024983DEVAppFolder folder.
        /// </summary>
        [RepositoryFolder("c78b5bd5-bad5-46ca-b813-c49e6b90339f")]
        public partial class Cwork2024983DEVAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuitemfichierInfo;

            /// <summary>
            /// Creates a new Cwork2024983DEV  folder.
            /// </summary>
            public Cwork2024983DEVAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Cwork2024983DEV", "/form[@title>'Cwork']", parentFolder, 30000, null, true, "c78b5bd5-bad5-46ca-b813-c49e6b90339f", "")
            {
                _menuitemfichierInfo = new RepoItemInfo(this, "MenuItemFichier", "menubar[@automationid='MenuBar']/menuitem[1]", "", 30000, null, "03b640d0-aa1a-48e6-b4b0-97ac7b849d83");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c78b5bd5-bad5-46ca-b813-c49e6b90339f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c78b5bd5-bad5-46ca-b813-c49e6b90339f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItemFichier item.
            /// </summary>
            [RepositoryItem("03b640d0-aa1a-48e6-b4b0-97ac7b849d83")]
            public virtual Ranorex.MenuItem MenuItemFichier
            {
                get
                {
                    return _menuitemfichierInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemFichier item info.
            /// </summary>
            [RepositoryItemInfo("03b640d0-aa1a-48e6-b4b0-97ac7b849d83")]
            public virtual RepoItemInfo MenuItemFichierInfo
            {
                get
                {
                    return _menuitemfichierInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
