///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint9_5_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Verify_Days3_Displayed recording.
    /// </summary>
    [TestModule("57163f77-be11-4ae8-b1f5-34dddc1435d5", ModuleType.Recording, 1)]
    public partial class Verify_Days3_Displayed : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_5_3Repository repository.
        /// </summary>
        public static Sprint_9_5_3Repository repo = Sprint_9_5_3Repository.Instance;

        static Verify_Days3_Displayed instance = new Verify_Days3_Displayed();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Verify_Days3_Displayed()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Verify_Days3_Displayed Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Verify_D_60cf3d4b_rxlog1' with region {X=0,Y=0,Width=50,Height=32}) on item 'CWork2021953DEV.SomeElement2'.", repo.CWork2021953DEV.SomeElement2Info, new RecordItemIndex(0));
            Validate.ContainsImage(repo.CWork2021953DEV.SomeElement2Info, SomeElement2_Verify_D_60cf3d4b_rxlog1, SomeElement2_Verify_D_60cf3d4b_rxlog1_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage SomeElement2_Verify_D_60cf3d4b_rxlog1
        { get { return repo.CWork2021953DEV.SomeElement2Info.GetVerify_D_60cf3d4b_rxlog1(new Rectangle(0, 0, 50, 32)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions SomeElement2_Verify_D_60cf3d4b_rxlog1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
