///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sprint_9_8_1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidatePrg1ReceivedInTed recording.
    /// </summary>
    [TestModule("664c8d9a-36ca-4309-9009-636ffadefd25", ModuleType.Recording, 1)]
    public partial class ValidatePrg1ReceivedInTed : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Sprint_9_8_1Repository repository.
        /// </summary>
        public static Sprint_9_8_1Repository repo = Sprint_9_8_1Repository.Instance;

        static ValidatePrg1ReceivedInTed instance = new ValidatePrg1ReceivedInTed();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidatePrg1ReceivedInTed()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidatePrg1ReceivedInTed Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 40s to exist. Associated repository item: 'FormTEDSCDemonstrationSoftwareV.ContainerDNC.RawTextIĈ'", repo.FormTEDSCDemonstrationSoftwareV.ContainerDNC.RawTextIĈInfo, new ActionTimeout(40000), new RecordItemIndex(0));
            repo.FormTEDSCDemonstrationSoftwareV.ContainerDNC.RawTextIĈInfo.WaitForExists(40000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (RawText='ÎĈ') on item 'FormTEDSCDemonstrationSoftwareV.ContainerDNC.RawTextIĈ'.", repo.FormTEDSCDemonstrationSoftwareV.ContainerDNC.RawTextIĈInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.FormTEDSCDemonstrationSoftwareV.ContainerDNC.RawTextIĈInfo, "RawText", "ÎĈ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (RawText='ĂŐǾŊĈÅ') on item 'FormTEDSCDemonstrationSoftwareV.ContainerDNC.ĂŐǾŊĈA'.", repo.FormTEDSCDemonstrationSoftwareV.ContainerDNC.ĂŐǾŊĈAInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.FormTEDSCDemonstrationSoftwareV.ContainerDNC.ĂŐǾŊĈAInfo, "RawText", "ĂŐǾŊĈÅ");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (RawText='ÌĊĆĂĜÍGÅ') on item 'FormTEDSCDemonstrationSoftwareV.ContainerDNC.IĊĆĂĜIGA'.", repo.FormTEDSCDemonstrationSoftwareV.ContainerDNC.IĊĆĂĜIGAInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.FormTEDSCDemonstrationSoftwareV.ContainerDNC.IĊĆĂĜIGAInfo, "RawText", "ÌĊĆĂĜÍGÅ");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
